/* Aria's Hindi Garden — content pack
   Each word: { hi: Devanagari, ro: romanization, en: English, ic: emoji }
   First-person sentences use feminine forms (Aria is a girl). */

const UNITS = [
  { id:"greet", name:"Hello & Manners", emoji:"👋", words:[
    {hi:"नमस्ते", ro:"namaste", en:"hello", ic:"🙏"},
    {hi:"नमस्कार", ro:"namaskaar", en:"greetings", ic:"🙏"},
    {hi:"अलविदा", ro:"alvida", en:"goodbye", ic:"👋"},
    {hi:"फिर मिलेंगे", ro:"phir milenge", en:"see you again", ic:"😊"},
    {hi:"शुक्रिया", ro:"shukriya", en:"thank you", ic:"😊"},
    {hi:"धन्यवाद", ro:"dhanyavaad", en:"thank you (formal)", ic:"🙏"},
    {hi:"कृपया", ro:"kripya", en:"please", ic:"🥺"},
    {hi:"माफ़ करना", ro:"maaf karna", en:"sorry", ic:"😔"},
    {hi:"कोई बात नहीं", ro:"koi baat nahin", en:"it's okay", ic:"🙂"},
    {hi:"हाँ", ro:"haan", en:"yes", ic:"✅"},
    {hi:"नहीं", ro:"nahin", en:"no", ic:"❌"},
    {hi:"ठीक है", ro:"theek hai", en:"okay / fine", ic:"👍"},
    {hi:"स्वागत है", ro:"swaagat hai", en:"welcome", ic:"🤗"},
    {hi:"शुभ प्रभात", ro:"shubh prabhaat", en:"good morning", ic:"🌅"},
    {hi:"शुभ रात्रि", ro:"shubh raatri", en:"good night", ic:"🌙"},
    {hi:"आपसे मिलकर खुशी हुई", ro:"aapse milkar khushi hui", en:"nice to meet you", ic:"😄"},
    {hi:"कैसे हो?", ro:"kaise ho?", en:"how are you?", ic:"🙂"},
    {hi:"मैं ठीक हूँ", ro:"main theek hoon", en:"I am fine", ic:"👍"},
  ]},

  { id:"family", name:"My Family", emoji:"👪", words:[
    {hi:"परिवार", ro:"parivaar", en:"family", ic:"👪"},
    {hi:"माँ", ro:"maa", en:"mom", ic:"👩"},
    {hi:"पापा", ro:"papa", en:"dad", ic:"👨"},
    {hi:"बेटी", ro:"beti", en:"daughter", ic:"👧"},
    {hi:"बेटा", ro:"beta", en:"son", ic:"👦"},
    {hi:"भाई", ro:"bhai", en:"brother", ic:"👦"},
    {hi:"बहन", ro:"bahan", en:"sister", ic:"👧"},
    {hi:"बड़ा भाई", ro:"bada bhai", en:"big brother", ic:"🧑"},
    {hi:"छोटी बहन", ro:"chhoti bahan", en:"little sister", ic:"👧"},
    {hi:"दादी", ro:"dadi", en:"grandma (dad's mom)", ic:"👵"},
    {hi:"दादा", ro:"dada", en:"grandpa (dad's dad)", ic:"👴"},
    {hi:"नानी", ro:"nani", en:"grandma (mom's mom)", ic:"👵"},
    {hi:"नाना", ro:"nana", en:"grandpa (mom's dad)", ic:"👴"},
    {hi:"चाचा", ro:"chacha", en:"uncle (dad's brother)", ic:"🧔"},
    {hi:"चाची", ro:"chachi", en:"aunt (chacha's wife)", ic:"👩"},
    {hi:"मामा", ro:"mama", en:"uncle (mom's brother)", ic:"🧔"},
    {hi:"मामी", ro:"mami", en:"aunt (mama's wife)", ic:"👩"},
    {hi:"बुआ", ro:"bua", en:"aunt (dad's sister)", ic:"👩"},
    {hi:"मौसी", ro:"mausi", en:"aunt (mom's sister)", ic:"👩"},
    {hi:"दोस्त", ro:"dost", en:"friend", ic:"🧒"},
    {hi:"बच्चा", ro:"baccha", en:"child", ic:"👶"},
    {hi:"लड़की", ro:"ladki", en:"girl", ic:"👧"},
    {hi:"लड़का", ro:"ladka", en:"boy", ic:"👦"},
  ]},

  { id:"feel", name:"Feelings & States", emoji:"😊", words:[
    {hi:"खुश", ro:"khush", en:"happy", ic:"😄"},
    {hi:"उदास", ro:"udaas", en:"sad", ic:"😢"},
    {hi:"गुस्सा", ro:"gussa", en:"angry", ic:"😠"},
    {hi:"डर", ro:"dar", en:"scared", ic:"😨"},
    {hi:"भूखा", ro:"bhookha", en:"hungry", ic:"🍽️"},
    {hi:"प्यासा", ro:"pyaasa", en:"thirsty", ic:"🥤"},
    {hi:"थका", ro:"thaka", en:"tired", ic:"🥱"},
    {hi:"बीमार", ro:"beemaar", en:"sick", ic:"🤒"},
    {hi:"ठीक", ro:"theek", en:"fine / okay", ic:"🙂"},
    {hi:"उत्साहित", ro:"utsaahit", en:"excited", ic:"🤩"},
    {hi:"शांत", ro:"shaant", en:"calm", ic:"😌"},
    {hi:"ऊब गया", ro:"oob gaya", en:"bored", ic:"😑"},
    {hi:"हैरान", ro:"hairaan", en:"surprised", ic:"😲"},
    {hi:"प्यार", ro:"pyaar", en:"love", ic:"❤️"},
    {hi:"अकेला", ro:"akela", en:"lonely", ic:"😔"},
    {hi:"नींद", ro:"neend", en:"sleepy", ic:"😴"},
    {hi:"गरम", ro:"garam", en:"hot", ic:"🥵"},
    {hi:"ठंडा", ro:"thanda", en:"cold", ic:"🥶"},
    {hi:"दर्द", ro:"dard", en:"pain / hurt", ic:"🤕"},
    {hi:"मज़ा", ro:"mazaa", en:"fun", ic:"🎉"},
    {hi:"गर्व", ro:"garv", en:"proud", ic:"😎"},
    {hi:"शर्म", ro:"sharm", en:"shy", ic:"😳"},
  ]},

  { id:"num", name:"Numbers", emoji:"🔢", words:[
    {hi:"शून्य", ro:"shoonya", en:"zero", ic:"0️⃣"},
    {hi:"एक", ro:"ek", en:"one", ic:"1️⃣"},
    {hi:"दो", ro:"do", en:"two", ic:"2️⃣"},
    {hi:"तीन", ro:"teen", en:"three", ic:"3️⃣"},
    {hi:"चार", ro:"chaar", en:"four", ic:"4️⃣"},
    {hi:"पाँच", ro:"paanch", en:"five", ic:"5️⃣"},
    {hi:"छह", ro:"chhah", en:"six", ic:"6️⃣"},
    {hi:"सात", ro:"saat", en:"seven", ic:"7️⃣"},
    {hi:"आठ", ro:"aath", en:"eight", ic:"8️⃣"},
    {hi:"नौ", ro:"nau", en:"nine", ic:"9️⃣"},
    {hi:"दस", ro:"das", en:"ten", ic:"🔟"},
    {hi:"ग्यारह", ro:"gyaarah", en:"eleven", ic:"🔢"},
    {hi:"बारह", ro:"baarah", en:"twelve", ic:"🔢"},
    {hi:"तेरह", ro:"terah", en:"thirteen", ic:"🔢"},
    {hi:"चौदह", ro:"chaudah", en:"fourteen", ic:"🔢"},
    {hi:"पंद्रह", ro:"pandrah", en:"fifteen", ic:"🔢"},
    {hi:"सोलह", ro:"solah", en:"sixteen", ic:"🔢"},
    {hi:"सत्रह", ro:"satrah", en:"seventeen", ic:"🔢"},
    {hi:"अठारह", ro:"athaarah", en:"eighteen", ic:"🔢"},
    {hi:"उन्नीस", ro:"unnees", en:"nineteen", ic:"🔢"},
    {hi:"बीस", ro:"bees", en:"twenty", ic:"🔢"},
    {hi:"तीस", ro:"tees", en:"thirty", ic:"🔢"},
    {hi:"चालीस", ro:"chaalees", en:"forty", ic:"🔢"},
    {hi:"पचास", ro:"pachaas", en:"fifty", ic:"🔢"},
    {hi:"साठ", ro:"saath", en:"sixty", ic:"🔢"},
    {hi:"सत्तर", ro:"sattar", en:"seventy", ic:"🔢"},
    {hi:"अस्सी", ro:"assee", en:"eighty", ic:"🔢"},
    {hi:"नब्बे", ro:"nabbe", en:"ninety", ic:"🔢"},
    {hi:"सौ", ro:"sau", en:"hundred", ic:"💯"},
  ]},

  { id:"color", name:"Colors", emoji:"🎨", words:[
    {hi:"रंग", ro:"rang", en:"color", ic:"🎨"},
    {hi:"लाल", ro:"laal", en:"red", ic:"🔴"},
    {hi:"नीला", ro:"neela", en:"blue", ic:"🔵"},
    {hi:"हरा", ro:"hara", en:"green", ic:"🟢"},
    {hi:"पीला", ro:"peela", en:"yellow", ic:"🟡"},
    {hi:"काला", ro:"kaala", en:"black", ic:"⚫"},
    {hi:"सफ़ेद", ro:"safed", en:"white", ic:"⚪"},
    {hi:"गुलाबी", ro:"gulaabi", en:"pink", ic:"🩷"},
    {hi:"नारंगी", ro:"naarangi", en:"orange", ic:"🟠"},
    {hi:"बैंगनी", ro:"baingani", en:"purple", ic:"🟣"},
    {hi:"भूरा", ro:"bhoora", en:"brown", ic:"🟤"},
    {hi:"सुनहरा", ro:"sunahra", en:"golden", ic:"🟨"},
    {hi:"चाँदी", ro:"chaandi", en:"silver", ic:"⬜"},
    {hi:"रंगीन", ro:"rangeen", en:"colorful", ic:"🌈"},
  ]},

  { id:"animal", name:"Animals", emoji:"🐘", words:[
    {hi:"जानवर", ro:"jaanvar", en:"animal", ic:"🐾"},
    {hi:"कुत्ता", ro:"kutta", en:"dog", ic:"🐶"},
    {hi:"बिल्ली", ro:"billi", en:"cat", ic:"🐱"},
    {hi:"गाय", ro:"gaay", en:"cow", ic:"🐮"},
    {hi:"भैंस", ro:"bhains", en:"buffalo", ic:"🐃"},
    {hi:"बकरी", ro:"bakri", en:"goat", ic:"🐐"},
    {hi:"भेड़", ro:"bhed", en:"sheep", ic:"🐑"},
    {hi:"घोड़ा", ro:"ghoda", en:"horse", ic:"🐴"},
    {hi:"गधा", ro:"gadha", en:"donkey", ic:"🫏"},
    {hi:"हाथी", ro:"haathi", en:"elephant", ic:"🐘"},
    {hi:"शेर", ro:"sher", en:"lion", ic:"🦁"},
    {hi:"बाघ", ro:"baagh", en:"tiger", ic:"🐯"},
    {hi:"भालू", ro:"bhaaloo", en:"bear", ic:"🐻"},
    {hi:"बंदर", ro:"bandar", en:"monkey", ic:"🐒"},
    {hi:"लोमड़ी", ro:"lomdi", en:"fox", ic:"🦊"},
    {hi:"खरगोश", ro:"khargosh", en:"rabbit", ic:"🐰"},
    {hi:"चूहा", ro:"chooha", en:"mouse", ic:"🐭"},
    {hi:"गिलहरी", ro:"gilahri", en:"squirrel", ic:"🐿️"},
    {hi:"हिरण", ro:"hiran", en:"deer", ic:"🦌"},
    {hi:"ऊँट", ro:"oont", en:"camel", ic:"🐫"},
    {hi:"सुअर", ro:"suar", en:"pig", ic:"🐷"},
    {hi:"मगरमच्छ", ro:"magarmachh", en:"crocodile", ic:"🐊"},
    {hi:"साँप", ro:"saanp", en:"snake", ic:"🐍"},
    {hi:"मेंढक", ro:"mendhak", en:"frog", ic:"🐸"},
    {hi:"मछली", ro:"machhli", en:"fish", ic:"🐟"},
    {hi:"कछुआ", ro:"kachhua", en:"turtle", ic:"🐢"},
    {hi:"चिड़िया", ro:"chidiya", en:"bird", ic:"🐦"},
    {hi:"तोता", ro:"tota", en:"parrot", ic:"🦜"},
    {hi:"मोर", ro:"mor", en:"peacock", ic:"🦚"},
    {hi:"कौआ", ro:"kauaa", en:"crow", ic:"🐦‍⬛"},
    {hi:"मुर्गा", ro:"murga", en:"rooster", ic:"🐓"},
    {hi:"तितली", ro:"titli", en:"butterfly", ic:"🦋"},
  ]},

  { id:"food", name:"Food & Drink", emoji:"🍱", words:[
    {hi:"खाना", ro:"khaana", en:"food", ic:"🍱"},
    {hi:"पानी", ro:"paani", en:"water", ic:"💧"},
    {hi:"दूध", ro:"doodh", en:"milk", ic:"🥛"},
    {hi:"रोटी", ro:"roti", en:"bread / roti", ic:"🫓"},
    {hi:"चावल", ro:"chaaval", en:"rice", ic:"🍚"},
    {hi:"दाल", ro:"daal", en:"lentils", ic:"🍲"},
    {hi:"सब्ज़ी", ro:"sabzi", en:"vegetable dish", ic:"🥘"},
    {hi:"अंडा", ro:"anda", en:"egg", ic:"🥚"},
    {hi:"पनीर", ro:"paneer", en:"cottage cheese", ic:"🧀"},
    {hi:"दही", ro:"dahi", en:"yogurt", ic:"🥣"},
    {hi:"मक्खन", ro:"makkhan", en:"butter", ic:"🧈"},
    {hi:"चीनी", ro:"cheeni", en:"sugar", ic:"🍬"},
    {hi:"नमक", ro:"namak", en:"salt", ic:"🧂"},
    {hi:"चाय", ro:"chaay", en:"tea", ic:"🍵"},
    {hi:"रस", ro:"ras", en:"juice", ic:"🧃"},
    {hi:"मिठाई", ro:"mithai", en:"sweets", ic:"🍮"},
    {hi:"बिस्कुट", ro:"biskut", en:"biscuit", ic:"🍪"},
    {hi:"समोसा", ro:"samosa", en:"samosa", ic:"🥟"},
    {hi:"खिचड़ी", ro:"khichdi", en:"khichdi", ic:"🍲"},
    {hi:"नाश्ता", ro:"naashta", en:"breakfast", ic:"🍳"},
    {hi:"दोपहर का खाना", ro:"dopahar ka khaana", en:"lunch", ic:"🍛"},
    {hi:"रात का खाना", ro:"raat ka khaana", en:"dinner", ic:"🍽️"},
    {hi:"भूख", ro:"bhookh", en:"hunger", ic:"😋"},
    {hi:"स्वादिष्ट", ro:"swaadisht", en:"delicious", ic:"😋"},
    {hi:"मीठा", ro:"meetha", en:"sweet", ic:"🍯"},
    {hi:"तीखा", ro:"teekha", en:"spicy", ic:"🌶️"},
  ]},

  { id:"fruitveg", name:"Fruits & Veggies", emoji:"🍎", words:[
    {hi:"फल", ro:"phal", en:"fruit", ic:"🍎"},
    {hi:"सेब", ro:"seb", en:"apple", ic:"🍎"},
    {hi:"केला", ro:"kela", en:"banana", ic:"🍌"},
    {hi:"आम", ro:"aam", en:"mango", ic:"🥭"},
    {hi:"संतरा", ro:"santra", en:"orange", ic:"🍊"},
    {hi:"अंगूर", ro:"angoor", en:"grapes", ic:"🍇"},
    {hi:"तरबूज़", ro:"tarbooz", en:"watermelon", ic:"🍉"},
    {hi:"अनार", ro:"anaar", en:"pomegranate", ic:"🫐"},
    {hi:"पपीता", ro:"papita", en:"papaya", ic:"🥭"},
    {hi:"अमरूद", ro:"amrood", en:"guava", ic:"🍈"},
    {hi:"नींबू", ro:"neemboo", en:"lemon", ic:"🍋"},
    {hi:"नाशपाती", ro:"naashpaati", en:"pear", ic:"🍐"},
    {hi:"स्ट्रॉबेरी", ro:"strawberry", en:"strawberry", ic:"🍓"},
    {hi:"सब्ज़ी", ro:"sabzi", en:"vegetable", ic:"🥦"},
    {hi:"आलू", ro:"aaloo", en:"potato", ic:"🥔"},
    {hi:"टमाटर", ro:"tamaatar", en:"tomato", ic:"🍅"},
    {hi:"प्याज़", ro:"pyaaz", en:"onion", ic:"🧅"},
    {hi:"गाजर", ro:"gaajar", en:"carrot", ic:"🥕"},
    {hi:"मटर", ro:"matar", en:"peas", ic:"🫛"},
    {hi:"भिंडी", ro:"bhindi", en:"okra", ic:"🥬"},
    {hi:"गोभी", ro:"gobhi", en:"cauliflower", ic:"🥦"},
    {hi:"खीरा", ro:"kheera", en:"cucumber", ic:"🥒"},
    {hi:"मक्का", ro:"makka", en:"corn", ic:"🌽"},
    {hi:"मिर्च", ro:"mirch", en:"chilli", ic:"🌶️"},
  ]},

  { id:"body", name:"My Body", emoji:"🧒", words:[
    {hi:"शरीर", ro:"shareer", en:"body", ic:"🧍"},
    {hi:"सिर", ro:"sir", en:"head", ic:"🧠"},
    {hi:"बाल", ro:"baal", en:"hair", ic:"💇"},
    {hi:"चेहरा", ro:"chehra", en:"face", ic:"😊"},
    {hi:"आँख", ro:"aankh", en:"eye", ic:"👁️"},
    {hi:"नाक", ro:"naak", en:"nose", ic:"👃"},
    {hi:"कान", ro:"kaan", en:"ear", ic:"👂"},
    {hi:"मुँह", ro:"munh", en:"mouth", ic:"👄"},
    {hi:"दाँत", ro:"daant", en:"tooth", ic:"🦷"},
    {hi:"जीभ", ro:"jeebh", en:"tongue", ic:"👅"},
    {hi:"गाल", ro:"gaal", en:"cheek", ic:"😊"},
    {hi:"गला", ro:"gala", en:"throat / neck", ic:"🧣"},
    {hi:"हाथ", ro:"haath", en:"hand", ic:"✋"},
    {hi:"उँगली", ro:"ungli", en:"finger", ic:"👆"},
    {hi:"बाँह", ro:"baanh", en:"arm", ic:"💪"},
    {hi:"पैर", ro:"pair", en:"foot / leg", ic:"🦶"},
    {hi:"घुटना", ro:"ghutna", en:"knee", ic:"🦵"},
    {hi:"पेट", ro:"pet", en:"stomach", ic:"🤰"},
    {hi:"पीठ", ro:"peeth", en:"back", ic:"🔙"},
    {hi:"दिल", ro:"dil", en:"heart", ic:"❤️"},
    {hi:"कंधा", ro:"kandha", en:"shoulder", ic:"💪"},
    {hi:"नाखून", ro:"naakhoon", en:"nail", ic:"💅"},
  ]},

  { id:"phrase", name:"Everyday Phrases", emoji:"💬", words:[
    {hi:"आप कैसे हैं?", ro:"aap kaise hain?", en:"how are you?", ic:"🙂"},
    {hi:"मैं ठीक हूँ", ro:"main theek hoon", en:"I am fine", ic:"👍"},
    {hi:"तुम्हारा नाम क्या है?", ro:"tumhara naam kya hai?", en:"what's your name?", ic:"❓"},
    {hi:"मेरा नाम आरिया है", ro:"mera naam Aria hai", en:"my name is Aria", ic:"🙋"},
    {hi:"तुम कहाँ रहती हो?", ro:"tum kahaan rahti ho?", en:"where do you live?", ic:"🏠"},
    {hi:"यह क्या है?", ro:"yeh kya hai?", en:"what is this?", ic:"❓"},
    {hi:"वह कौन है?", ro:"vah kaun hai?", en:"who is that?", ic:"👤"},
    {hi:"कितने बजे हैं?", ro:"kitne baje hain?", en:"what time is it?", ic:"🕐"},
    {hi:"मुझे भूख लगी है", ro:"mujhe bhookh lagi hai", en:"I am hungry", ic:"🍽️"},
    {hi:"मुझे प्यास लगी है", ro:"mujhe pyaas lagi hai", en:"I am thirsty", ic:"🥤"},
    {hi:"मुझे पानी चाहिए", ro:"mujhe paani chahiye", en:"I want water", ic:"💧"},
    {hi:"मुझे यह पसंद है", ro:"mujhe yeh pasand hai", en:"I like this", ic:"❤️"},
    {hi:"मुझे यह पसंद नहीं है", ro:"mujhe yeh pasand nahin hai", en:"I don't like this", ic:"🙅"},
    {hi:"चलो खेलते हैं", ro:"chalo khelte hain", en:"let's play", ic:"🎈"},
    {hi:"मुझे माफ़ करना", ro:"mujhe maaf karna", en:"forgive me / sorry", ic:"😔"},
    {hi:"बहुत अच्छा", ro:"bahut achha", en:"very good", ic:"👍"},
    {hi:"शाबाश", ro:"shaabaash", en:"well done", ic:"👏"},
    {hi:"रुको", ro:"ruko", en:"wait / stop", ic:"✋"},
    {hi:"जल्दी करो", ro:"jaldi karo", en:"hurry up", ic:"⏰"},
    {hi:"धीरे चलो", ro:"dheere chalo", en:"go slowly", ic:"🐢"},
    {hi:"मुझे नहीं पता", ro:"mujhe nahin pata", en:"I don't know", ic:"🤷"},
    {hi:"मुझे पता है", ro:"mujhe pata hai", en:"I know", ic:"💡"},
    {hi:"फिर से कहो", ro:"phir se kaho", en:"say it again", ic:"🔁"},
    {hi:"समझ गई", ro:"samajh gayi", en:"I understood", ic:"✅"},
    {hi:"कोई बात नहीं", ro:"koi baat nahin", en:"no problem", ic:"🙂"},
    {hi:"बधाई हो", ro:"badhaai ho", en:"congratulations", ic:"🎉"},
  ]},

  { id:"ask", name:"Asking & Wanting", emoji:"🙋", words:[
    {hi:"मुझे यह दे दो", ro:"mujhe yeh de do", en:"give me this", ic:"🤲"},
    {hi:"क्या मैं खेल सकती हूँ?", ro:"kya main khel sakti hoon?", en:"can I play?", ic:"🎮"},
    {hi:"क्या मैं अंदर आ सकती हूँ?", ro:"kya main andar aa sakti hoon?", en:"can I come in?", ic:"🚪"},
    {hi:"मुझे मदद चाहिए", ro:"mujhe madad chahiye", en:"I need help", ic:"🆘"},
    {hi:"कृपया मेरी मदद करो", ro:"kripya meri madad karo", en:"please help me", ic:"🙏"},
    {hi:"यह कहाँ है?", ro:"yeh kahaan hai?", en:"where is this?", ic:"🔍"},
    {hi:"क्यों?", ro:"kyon?", en:"why?", ic:"❓"},
    {hi:"कैसे?", ro:"kaise?", en:"how?", ic:"❓"},
    {hi:"कब?", ro:"kab?", en:"when?", ic:"🕐"},
    {hi:"कौन सा?", ro:"kaun sa?", en:"which one?", ic:"👉"},
    {hi:"कितना?", ro:"kitna?", en:"how much?", ic:"🔢"},
    {hi:"मुझे समझ नहीं आया", ro:"mujhe samajh nahin aaya", en:"I don't understand", ic:"🤔"},
    {hi:"एक मिनट रुको", ro:"ek minute ruko", en:"wait a minute", ic:"⏳"},
    {hi:"क्या मैं जा सकती हूँ?", ro:"kya main ja sakti hoon?", en:"can I go?", ic:"🚶"},
    {hi:"मुझे यह चाहिए", ro:"mujhe yeh chahiye", en:"I want this", ic:"🙋"},
    {hi:"मुझे और चाहिए", ro:"mujhe aur chahiye", en:"I want more", ic:"➕"},
    {hi:"बस, बहुत हुआ", ro:"bas, bahut hua", en:"that's enough", ic:"🛑"},
    {hi:"क्या यह सही है?", ro:"kya yeh sahi hai?", en:"is this correct?", ic:"✔️"},
  ]},

  { id:"day", name:"My Day & Routine", emoji:"🌞", words:[
    {hi:"शुभ प्रभात", ro:"shubh prabhaat", en:"good morning", ic:"🌅"},
    {hi:"शुभ रात्रि", ro:"shubh raatri", en:"good night", ic:"🌙"},
    {hi:"मैं उठ गई", ro:"main uth gayi", en:"I woke up", ic:"🛏️"},
    {hi:"मैं दाँत साफ़ करती हूँ", ro:"main daant saaf karti hoon", en:"I brush my teeth", ic:"🪥"},
    {hi:"मैं नहाती हूँ", ro:"main nahaati hoon", en:"I take a bath", ic:"🛁"},
    {hi:"मैं कपड़े पहनती हूँ", ro:"main kapde pehenti hoon", en:"I get dressed", ic:"👕"},
    {hi:"मैं नाश्ता करती हूँ", ro:"main naashta karti hoon", en:"I eat breakfast", ic:"🍳"},
    {hi:"मैं स्कूल जाती हूँ", ro:"main school jaati hoon", en:"I go to school", ic:"🎒"},
    {hi:"मैं पढ़ती हूँ", ro:"main padhti hoon", en:"I study", ic:"📚"},
    {hi:"मैं खेलती हूँ", ro:"main khelti hoon", en:"I play", ic:"⚽"},
    {hi:"मैं खाना खाती हूँ", ro:"main khaana khaati hoon", en:"I eat food", ic:"🍱"},
    {hi:"मैं सोती हूँ", ro:"main soti hoon", en:"I sleep", ic:"😴"},
    {hi:"मुझे नींद आ रही है", ro:"mujhe neend aa rahi hai", en:"I feel sleepy", ic:"🥱"},
    {hi:"मैं तैयार हूँ", ro:"main taiyaar hoon", en:"I am ready", ic:"✅"},
    {hi:"सुबह", ro:"subah", en:"morning", ic:"🌅"},
    {hi:"दोपहर", ro:"dopahar", en:"afternoon", ic:"☀️"},
    {hi:"शाम", ro:"shaam", en:"evening", ic:"🌇"},
    {hi:"रात", ro:"raat", en:"night", ic:"🌙"},
    {hi:"आज", ro:"aaj", en:"today", ic:"📅"},
    {hi:"कल", ro:"kal", en:"tomorrow / yesterday", ic:"📆"},
    {hi:"अभी", ro:"abhi", en:"right now", ic:"⏱️"},
    {hi:"बाद में", ro:"baad mein", en:"later", ic:"⏳"},
  ]},

  { id:"home", name:"Home & Rooms", emoji:"🏠", words:[
    {hi:"घर", ro:"ghar", en:"home / house", ic:"🏠"},
    {hi:"कमरा", ro:"kamra", en:"room", ic:"🚪"},
    {hi:"रसोई", ro:"rasoi", en:"kitchen", ic:"🍳"},
    {hi:"बिस्तर", ro:"bistar", en:"bed", ic:"🛏️"},
    {hi:"दरवाज़ा", ro:"darvaaza", en:"door", ic:"🚪"},
    {hi:"खिड़की", ro:"khidki", en:"window", ic:"🪟"},
    {hi:"कुर्सी", ro:"kursi", en:"chair", ic:"🪑"},
    {hi:"मेज़", ro:"mez", en:"table", ic:"🪑"},
    {hi:"दीवार", ro:"deevaar", en:"wall", ic:"🧱"},
    {hi:"छत", ro:"chhat", en:"roof / ceiling", ic:"🏠"},
    {hi:"फ़र्श", ro:"farsh", en:"floor", ic:"⬜"},
    {hi:"सीढ़ी", ro:"seedhi", en:"stairs", ic:"🪜"},
    {hi:"बाथरूम", ro:"bathroom", en:"bathroom", ic:"🚽"},
    {hi:"पंखा", ro:"pankha", en:"fan", ic:"🌀"},
    {hi:"बत्ती", ro:"batti", en:"light", ic:"💡"},
    {hi:"चाबी", ro:"chaabi", en:"key", ic:"🔑"},
    {hi:"घड़ी", ro:"ghadi", en:"clock / watch", ic:"⏰"},
    {hi:"तकिया", ro:"takiya", en:"pillow", ic:"🛏️"},
    {hi:"कंबल", ro:"kambal", en:"blanket", ic:"🛌"},
    {hi:"बर्तन", ro:"bartan", en:"dishes / utensils", ic:"🍽️"},
    {hi:"गिलास", ro:"gilaas", en:"glass", ic:"🥛"},
    {hi:"चम्मच", ro:"chammach", en:"spoon", ic:"🥄"},
  ]},

  { id:"clothes", name:"Clothes", emoji:"👕", words:[
    {hi:"कपड़े", ro:"kapde", en:"clothes", ic:"👚"},
    {hi:"कमीज़", ro:"kameez", en:"shirt", ic:"👕"},
    {hi:"पैंट", ro:"pant", en:"pants", ic:"👖"},
    {hi:"फ्रॉक", ro:"frock", en:"frock / dress", ic:"👗"},
    {hi:"साड़ी", ro:"saari", en:"saree", ic:"🥻"},
    {hi:"कुर्ता", ro:"kurta", en:"kurta", ic:"👘"},
    {hi:"टोपी", ro:"topi", en:"cap / hat", ic:"🧢"},
    {hi:"जूता", ro:"joota", en:"shoe", ic:"👟"},
    {hi:"मोज़ा", ro:"moza", en:"sock", ic:"🧦"},
    {hi:"चप्पल", ro:"chappal", en:"slipper", ic:"🩴"},
    {hi:"स्वेटर", ro:"sweater", en:"sweater", ic:"🧥"},
    {hi:"जैकेट", ro:"jacket", en:"jacket", ic:"🧥"},
    {hi:"दुपट्टा", ro:"dupatta", en:"scarf", ic:"🧣"},
    {hi:"बेल्ट", ro:"belt", en:"belt", ic:"➰"},
    {hi:"चश्मा", ro:"chashma", en:"glasses", ic:"👓"},
    {hi:"छाता", ro:"chhaata", en:"umbrella", ic:"☂️"},
    {hi:"बटन", ro:"button", en:"button", ic:"🔘"},
    {hi:"रुमाल", ro:"rumaal", en:"handkerchief", ic:"🧻"},
  ]},

  { id:"nature", name:"Nature & Weather", emoji:"🌳", words:[
    {hi:"सूरज", ro:"sooraj", en:"sun", ic:"☀️"},
    {hi:"चाँद", ro:"chaand", en:"moon", ic:"🌙"},
    {hi:"तारा", ro:"taara", en:"star", ic:"⭐"},
    {hi:"आसमान", ro:"aasmaan", en:"sky", ic:"🌌"},
    {hi:"बादल", ro:"baadal", en:"cloud", ic:"☁️"},
    {hi:"बारिश", ro:"baarish", en:"rain", ic:"🌧️"},
    {hi:"हवा", ro:"hava", en:"wind / air", ic:"💨"},
    {hi:"धूप", ro:"dhoop", en:"sunshine", ic:"🌞"},
    {hi:"पेड़", ro:"ped", en:"tree", ic:"🌳"},
    {hi:"पत्ता", ro:"patta", en:"leaf", ic:"🍃"},
    {hi:"फूल", ro:"phool", en:"flower", ic:"🌸"},
    {hi:"घास", ro:"ghaas", en:"grass", ic:"🌱"},
    {hi:"नदी", ro:"nadi", en:"river", ic:"🏞️"},
    {hi:"समुंदर", ro:"samundar", en:"sea", ic:"🌊"},
    {hi:"पहाड़", ro:"pahaad", en:"mountain", ic:"⛰️"},
    {hi:"आग", ro:"aag", en:"fire", ic:"🔥"},
    {hi:"मिट्टी", ro:"mitti", en:"soil / mud", ic:"🟫"},
    {hi:"पत्थर", ro:"patthar", en:"stone", ic:"🪨"},
    {hi:"बर्फ़", ro:"barf", en:"snow / ice", ic:"❄️"},
    {hi:"इंद्रधनुष", ro:"indradhanush", en:"rainbow", ic:"🌈"},
    {hi:"मौसम", ro:"mausam", en:"weather", ic:"🌤️"},
    {hi:"गरमी", ro:"garmi", en:"summer / heat", ic:"🥵"},
  ]},

  { id:"school", name:"School & Learning", emoji:"🏫", words:[
    {hi:"स्कूल", ro:"school", en:"school", ic:"🏫"},
    {hi:"किताब", ro:"kitaab", en:"book", ic:"📖"},
    {hi:"कलम", ro:"kalam", en:"pen", ic:"🖊️"},
    {hi:"पेंसिल", ro:"pencil", en:"pencil", ic:"✏️"},
    {hi:"कागज़", ro:"kaagaz", en:"paper", ic:"📄"},
    {hi:"कॉपी", ro:"copy", en:"notebook", ic:"📓"},
    {hi:"बस्ता", ro:"basta", en:"school bag", ic:"🎒"},
    {hi:"रबर", ro:"rabar", en:"eraser", ic:"🧽"},
    {hi:"पढ़ाई", ro:"padhaai", en:"studies", ic:"📚"},
    {hi:"अध्यापक", ro:"adhyaapak", en:"teacher", ic:"🧑‍🏫"},
    {hi:"छात्र", ro:"chhaatra", en:"student", ic:"🧑‍🎓"},
    {hi:"कक्षा", ro:"kaksha", en:"class", ic:"🏫"},
    {hi:"सवाल", ro:"sawaal", en:"question", ic:"❓"},
    {hi:"जवाब", ro:"jawaab", en:"answer", ic:"💬"},
    {hi:"अक्षर", ro:"akshar", en:"letter (alphabet)", ic:"🔤"},
    {hi:"शब्द", ro:"shabd", en:"word", ic:"🔡"},
    {hi:"गिनती", ro:"ginti", en:"counting", ic:"🔢"},
    {hi:"चित्र", ro:"chitra", en:"picture", ic:"🖼️"},
    {hi:"खेल", ro:"khel", en:"game / sport", ic:"⚽"},
    {hi:"छुट्टी", ro:"chhutti", en:"holiday / break", ic:"🏖️"},
    {hi:"सीखना", ro:"seekhna", en:"to learn", ic:"🧠"},
    {hi:"होशियार", ro:"hoshiyaar", en:"clever", ic:"🤓"},
  ]},

  { id:"actions", name:"Action Words", emoji:"🏃", words:[
    {hi:"जाना", ro:"jaana", en:"to go", ic:"🚶"},
    {hi:"आना", ro:"aana", en:"to come", ic:"🏃"},
    {hi:"खाना", ro:"khaana", en:"to eat", ic:"🍴"},
    {hi:"पीना", ro:"peena", en:"to drink", ic:"🥤"},
    {hi:"सोना", ro:"sona", en:"to sleep", ic:"😴"},
    {hi:"उठना", ro:"uthna", en:"to get up", ic:"🛏️"},
    {hi:"बैठना", ro:"baithna", en:"to sit", ic:"🪑"},
    {hi:"खड़ा होना", ro:"khada hona", en:"to stand", ic:"🧍"},
    {hi:"चलना", ro:"chalna", en:"to walk", ic:"🚶"},
    {hi:"दौड़ना", ro:"daudna", en:"to run", ic:"🏃"},
    {hi:"कूदना", ro:"koodna", en:"to jump", ic:"🤸"},
    {hi:"हँसना", ro:"hansna", en:"to laugh", ic:"😄"},
    {hi:"रोना", ro:"rona", en:"to cry", ic:"😭"},
    {hi:"बोलना", ro:"bolna", en:"to speak", ic:"🗣️"},
    {hi:"सुनना", ro:"sunna", en:"to listen", ic:"👂"},
    {hi:"देखना", ro:"dekhna", en:"to see", ic:"👀"},
    {hi:"पढ़ना", ro:"padhna", en:"to read", ic:"📖"},
    {hi:"लिखना", ro:"likhna", en:"to write", ic:"✍️"},
    {hi:"खेलना", ro:"khelna", en:"to play", ic:"🎮"},
    {hi:"गाना", ro:"gaana", en:"to sing", ic:"🎤"},
    {hi:"नाचना", ro:"naachna", en:"to dance", ic:"💃"},
    {hi:"धोना", ro:"dhona", en:"to wash", ic:"🧼"},
    {hi:"खोलना", ro:"kholna", en:"to open", ic:"🔓"},
    {hi:"बंद करना", ro:"band karna", en:"to close", ic:"🔒"},
    {hi:"देना", ro:"dena", en:"to give", ic:"🤲"},
    {hi:"लेना", ro:"lena", en:"to take", ic:"🫳"},
    {hi:"रुकना", ro:"rukna", en:"to stop", ic:"✋"},
    {hi:"मदद करना", ro:"madad karna", en:"to help", ic:"🤝"},
  ]},

  { id:"describe", name:"Describing & Opposites", emoji:"↔️", words:[
    {hi:"बड़ा", ro:"bada", en:"big", ic:"🐘"},
    {hi:"छोटा", ro:"chhota", en:"small", ic:"🐜"},
    {hi:"लंबा", ro:"lamba", en:"tall / long", ic:"📏"},
    {hi:"छोटा कद", ro:"chhota kad", en:"short", ic:"📐"},
    {hi:"मोटा", ro:"mota", en:"fat / thick", ic:"🐷"},
    {hi:"पतला", ro:"patla", en:"thin", ic:"🥢"},
    {hi:"नया", ro:"naya", en:"new", ic:"🆕"},
    {hi:"पुराना", ro:"purana", en:"old", ic:"📜"},
    {hi:"अच्छा", ro:"achha", en:"good", ic:"👍"},
    {hi:"बुरा", ro:"bura", en:"bad", ic:"👎"},
    {hi:"साफ़", ro:"saaf", en:"clean", ic:"✨"},
    {hi:"गंदा", ro:"ganda", en:"dirty", ic:"🧹"},
    {hi:"गरम", ro:"garam", en:"hot", ic:"🔥"},
    {hi:"ठंडा", ro:"thanda", en:"cold", ic:"❄️"},
    {hi:"तेज़", ro:"tez", en:"fast", ic:"⚡"},
    {hi:"धीमा", ro:"dheema", en:"slow", ic:"🐢"},
    {hi:"ऊँचा", ro:"ooncha", en:"high", ic:"⬆️"},
    {hi:"नीचा", ro:"neecha", en:"low", ic:"⬇️"},
    {hi:"खुला", ro:"khula", en:"open", ic:"🔓"},
    {hi:"बंद", ro:"band", en:"closed", ic:"🔒"},
    {hi:"भारी", ro:"bhaari", en:"heavy", ic:"🏋️"},
    {hi:"हल्का", ro:"halka", en:"light (weight)", ic:"🪶"},
    {hi:"खुश", ro:"khush", en:"happy", ic:"😄"},
    {hi:"सुंदर", ro:"sundar", en:"beautiful", ic:"🌸"},
  ]},

  { id:"time", name:"Time, Days & Months", emoji:"📅", words:[
    {hi:"समय", ro:"samay", en:"time", ic:"⏰"},
    {hi:"दिन", ro:"din", en:"day", ic:"📅"},
    {hi:"हफ़्ता", ro:"hafta", en:"week", ic:"🗓️"},
    {hi:"महीना", ro:"maheena", en:"month", ic:"📆"},
    {hi:"साल", ro:"saal", en:"year", ic:"🎍"},
    {hi:"घंटा", ro:"ghanta", en:"hour", ic:"⏳"},
    {hi:"मिनट", ro:"minute", en:"minute", ic:"⏱️"},
    {hi:"सोमवार", ro:"somvaar", en:"Monday", ic:"1️⃣"},
    {hi:"मंगलवार", ro:"mangalvaar", en:"Tuesday", ic:"2️⃣"},
    {hi:"बुधवार", ro:"budhvaar", en:"Wednesday", ic:"3️⃣"},
    {hi:"गुरुवार", ro:"guruvaar", en:"Thursday", ic:"4️⃣"},
    {hi:"शुक्रवार", ro:"shukravaar", en:"Friday", ic:"5️⃣"},
    {hi:"शनिवार", ro:"shanivaar", en:"Saturday", ic:"6️⃣"},
    {hi:"रविवार", ro:"ravivaar", en:"Sunday", ic:"7️⃣"},
    {hi:"जनवरी", ro:"janvari", en:"January", ic:"❄️"},
    {hi:"फ़रवरी", ro:"farvari", en:"February", ic:"💝"},
    {hi:"मार्च", ro:"march", en:"March", ic:"🌷"},
    {hi:"अप्रैल", ro:"april", en:"April", ic:"🌧️"},
    {hi:"मई", ro:"mai", en:"May", ic:"🌞"},
    {hi:"जून", ro:"joon", en:"June", ic:"🏖️"},
    {hi:"जुलाई", ro:"julaai", en:"July", ic:"☀️"},
    {hi:"अगस्त", ro:"agast", en:"August", ic:"🌻"},
    {hi:"सितंबर", ro:"sitambar", en:"September", ic:"🍂"},
    {hi:"अक्टूबर", ro:"aktoobar", en:"October", ic:"🎃"},
    {hi:"नवंबर", ro:"navambar", en:"November", ic:"🍁"},
    {hi:"दिसंबर", ro:"disambar", en:"December", ic:"🎄"},
  ]},

  { id:"places", name:"Places Around Town", emoji:"🏙️", words:[
    {hi:"बाज़ार", ro:"baazaar", en:"market", ic:"🛒"},
    {hi:"दुकान", ro:"dukaan", en:"shop", ic:"🏪"},
    {hi:"अस्पताल", ro:"aspataal", en:"hospital", ic:"🏥"},
    {hi:"पार्क", ro:"park", en:"park", ic:"🏞️"},
    {hi:"मंदिर", ro:"mandir", en:"temple", ic:"🛕"},
    {hi:"सड़क", ro:"sadak", en:"road", ic:"🛣️"},
    {hi:"पुल", ro:"pul", en:"bridge", ic:"🌉"},
    {hi:"बैंक", ro:"bank", en:"bank", ic:"🏦"},
    {hi:"डाकघर", ro:"daakghar", en:"post office", ic:"🏤"},
    {hi:"रेलवे स्टेशन", ro:"railway station", en:"train station", ic:"🚉"},
    {hi:"हवाई अड्डा", ro:"havaai adda", en:"airport", ic:"✈️"},
    {hi:"चिड़ियाघर", ro:"chidiyaghar", en:"zoo", ic:"🦓"},
    {hi:"खेत", ro:"khet", en:"farm / field", ic:"🌾"},
    {hi:"गाँव", ro:"gaanv", en:"village", ic:"🏘️"},
    {hi:"शहर", ro:"shahar", en:"city", ic:"🏙️"},
    {hi:"समुंदर किनारा", ro:"samundar kinaara", en:"beach", ic:"🏖️"},
    {hi:"पुस्तकालय", ro:"pustakaalaya", en:"library", ic:"📚"},
    {hi:"रेस्टोरेंट", ro:"restaurant", en:"restaurant", ic:"🍽️"},
  ]},

  { id:"vehicles", name:"Vehicles", emoji:"🚗", words:[
    {hi:"गाड़ी", ro:"gaadi", en:"car / vehicle", ic:"🚗"},
    {hi:"बस", ro:"bas", en:"bus", ic:"🚌"},
    {hi:"रेलगाड़ी", ro:"relgaadi", en:"train", ic:"🚂"},
    {hi:"हवाई जहाज़", ro:"havaai jahaaz", en:"airplane", ic:"✈️"},
    {hi:"साइकिल", ro:"cycle", en:"bicycle", ic:"🚲"},
    {hi:"मोटरसाइकिल", ro:"motorcycle", en:"motorcycle", ic:"🏍️"},
    {hi:"नाव", ro:"naav", en:"boat", ic:"⛵"},
    {hi:"जहाज़", ro:"jahaaz", en:"ship", ic:"🚢"},
    {hi:"रिक्शा", ro:"riksha", en:"rickshaw", ic:"🛺"},
    {hi:"ट्रक", ro:"truck", en:"truck", ic:"🚚"},
    {hi:"टैक्सी", ro:"taxi", en:"taxi", ic:"🚕"},
    {hi:"रॉकेट", ro:"rocket", en:"rocket", ic:"🚀"},
    {hi:"हेलीकॉप्टर", ro:"helicopter", en:"helicopter", ic:"🚁"},
    {hi:"पहिया", ro:"pahiya", en:"wheel", ic:"⚙️"},
  ]},

  { id:"toys", name:"Toys & Play", emoji:"🧸", words:[
    {hi:"खिलौना", ro:"khilauna", en:"toy", ic:"🧸"},
    {hi:"गेंद", ro:"gend", en:"ball", ic:"⚽"},
    {hi:"गुड़िया", ro:"gudiya", en:"doll", ic:"🪆"},
    {hi:"गुब्बारा", ro:"gubbaara", en:"balloon", ic:"🎈"},
    {hi:"पतंग", ro:"patang", en:"kite", ic:"🪁"},
    {hi:"ब्लॉक", ro:"block", en:"blocks", ic:"🧱"},
    {hi:"झूला", ro:"jhoola", en:"swing", ic:"🛝"},
    {hi:"फिसलपट्टी", ro:"phisalpatti", en:"slide", ic:"🛝"},
    {hi:"रंग", ro:"rang", en:"paint / colors", ic:"🎨"},
    {hi:"चित्रकारी", ro:"chitrakaari", en:"drawing", ic:"🖍️"},
    {hi:"पहेली", ro:"paheli", en:"puzzle / riddle", ic:"🧩"},
    {hi:"कहानी", ro:"kahaani", en:"story", ic:"📖"},
    {hi:"गाना", ro:"gaana", en:"song", ic:"🎵"},
    {hi:"दोस्त", ro:"dost", en:"friend", ic:"🧒"},
  ]},

  { id:"sentences", name:"Bigger Sentences", emoji:"💪", words:[
    {hi:"मुझे आम बहुत पसंद हैं", ro:"mujhe aam bahut pasand hain", en:"I really like mangoes", ic:"🥭"},
    {hi:"मेरी माँ बहुत अच्छी हैं", ro:"meri maa bahut achhi hain", en:"my mom is very nice", ic:"👩"},
    {hi:"आज मैंने बहुत मज़ा किया", ro:"aaj maine bahut mazaa kiya", en:"I had lots of fun today", ic:"🎉"},
    {hi:"क्या हम बाहर जा सकते हैं?", ro:"kya hum baahar ja sakte hain?", en:"can we go outside?", ic:"🌳"},
    {hi:"मुझे तुमसे प्यार है", ro:"mujhe tumse pyaar hai", en:"I love you", ic:"❤️"},
    {hi:"मैं हिंदी सीख रही हूँ", ro:"main hindi seekh rahi hoon", en:"I am learning Hindi", ic:"📚"},
    {hi:"आज मौसम बहुत अच्छा है", ro:"aaj mausam bahut achha hai", en:"the weather is very nice today", ic:"☀️"},
    {hi:"मैं अपने दोस्त के साथ खेलती हूँ", ro:"main apne dost ke saath khelti hoon", en:"I play with my friend", ic:"🧒"},
    {hi:"मुझे कहानियाँ सुनना अच्छा लगता है", ro:"mujhe kahaaniyaan sunna achha lagta hai", en:"I like listening to stories", ic:"📖"},
    {hi:"क्या तुम मेरे साथ चलोगी?", ro:"kya tum mere saath chalogi?", en:"will you come with me?", ic:"🙋"},
    {hi:"मैंने अपना काम पूरा कर लिया", ro:"maine apna kaam poora kar liya", en:"I finished my work", ic:"✅"},
    {hi:"मुझे थोड़ी मदद चाहिए", ro:"mujhe thodi madad chahiye", en:"I need a little help", ic:"🤝"},
    {hi:"यह मेरी पसंदीदा किताब है", ro:"yeh meri pasandeeda kitaab hai", en:"this is my favorite book", ic:"📕"},
    {hi:"हम कल पार्क जाएँगे", ro:"hum kal park jaayenge", en:"we will go to the park tomorrow", ic:"🏞️"},
    {hi:"मैं बहुत खुश हूँ", ro:"main bahut khush hoon", en:"I am very happy", ic:"😄"},
    {hi:"मुझे यह खेल बहुत पसंद है", ro:"mujhe yeh khel bahut pasand hai", en:"I really like this game", ic:"🎮"},
    {hi:"क्या मैं तुम्हारी मदद करूँ?", ro:"kya main tumhari madad karoon?", en:"shall I help you?", ic:"🤲"},
    {hi:"धन्यवाद, तुम बहुत अच्छे हो", ro:"dhanyavaad, tum bahut achhe ho", en:"thank you, you are very kind", ic:"🙏"},
  ]},
];

const CONVOS = [
  { id:"c1", name:"Saying Hello", emoji:"👋", lines:[
    {sp:"A", hi:"नमस्ते!", ro:"namaste!", en:"Hello!"},
    {sp:"B", hi:"नमस्ते! तुम कैसी हो?", ro:"namaste! tum kaisi ho?", en:"Hello! How are you?"},
    {sp:"A", hi:"मैं ठीक हूँ, शुक्रिया। और तुम?", ro:"main theek hoon, shukriya. aur tum?", en:"I'm fine, thank you. And you?"},
    {sp:"B", hi:"मैं भी ठीक हूँ।", ro:"main bhi theek hoon.", en:"I'm fine too."},
    {sp:"A", hi:"फिर मिलेंगे!", ro:"phir milenge!", en:"See you again!"},
  ]},
  { id:"c2", name:"At Snack Time", emoji:"🍎", lines:[
    {sp:"A", hi:"मुझे भूख लगी है।", ro:"mujhe bhookh lagi hai.", en:"I am hungry."},
    {sp:"B", hi:"क्या तुम्हें सेब चाहिए?", ro:"kya tumhein seb chahiye?", en:"Do you want an apple?"},
    {sp:"A", hi:"हाँ, कृपया!", ro:"haan, kripya!", en:"Yes, please!"},
    {sp:"B", hi:"यह लो।", ro:"yeh lo.", en:"Here you go."},
    {sp:"A", hi:"बहुत स्वादिष्ट है। शुक्रिया!", ro:"bahut swaadisht hai. shukriya!", en:"It's very tasty. Thank you!"},
  ]},
  { id:"c3", name:"Meeting a Friend", emoji:"🧒", lines:[
    {sp:"A", hi:"तुम्हारा नाम क्या है?", ro:"tumhara naam kya hai?", en:"What's your name?"},
    {sp:"B", hi:"मेरा नाम आरिया है। और तुम्हारा?", ro:"mera naam Aria hai. aur tumhara?", en:"My name is Aria. And yours?"},
    {sp:"A", hi:"मेरा नाम रवि है।", ro:"mera naam Ravi hai.", en:"My name is Ravi."},
    {sp:"B", hi:"आपसे मिलकर खुशी हुई!", ro:"aapse milkar khushi hui!", en:"Nice to meet you!"},
    {sp:"A", hi:"चलो खेलते हैं!", ro:"chalo khelte hain!", en:"Let's play!"},
  ]},
  { id:"c4", name:"Good Morning", emoji:"🌅", lines:[
    {sp:"A", hi:"शुभ प्रभात!", ro:"shubh prabhaat!", en:"Good morning!"},
    {sp:"B", hi:"शुभ प्रभात! क्या तुम उठ गई?", ro:"shubh prabhaat! kya tum uth gayi?", en:"Good morning! Did you wake up?"},
    {sp:"A", hi:"हाँ, मैं तैयार हूँ।", ro:"haan, main taiyaar hoon.", en:"Yes, I am ready."},
    {sp:"B", hi:"चलो नाश्ता करते हैं।", ro:"chalo naashta karte hain.", en:"Let's eat breakfast."},
    {sp:"A", hi:"मुझे दूध चाहिए।", ro:"mujhe doodh chahiye.", en:"I want milk."},
  ]},
  { id:"c5", name:"At the Park", emoji:"🏞️", lines:[
    {sp:"A", hi:"चलो पार्क चलते हैं।", ro:"chalo park chalte hain.", en:"Let's go to the park."},
    {sp:"B", hi:"मैं झूला झूलना चाहती हूँ।", ro:"main jhoola jhoolna chahti hoon.", en:"I want to swing."},
    {sp:"A", hi:"मैं फिसलपट्टी पर खेलूँगी।", ro:"main phisalpatti par kheloongi.", en:"I will play on the slide."},
    {sp:"B", hi:"देखो, कितनी सुंदर तितली!", ro:"dekho, kitni sundar titli!", en:"Look, what a beautiful butterfly!"},
    {sp:"A", hi:"बहुत मज़ा आ रहा है!", ro:"bahut mazaa aa raha hai!", en:"This is so much fun!"},
  ]},
  { id:"c6", name:"Bedtime", emoji:"🌙", lines:[
    {sp:"A", hi:"मुझे नींद आ रही है।", ro:"mujhe neend aa rahi hai.", en:"I am feeling sleepy."},
    {sp:"B", hi:"चलो सोने का समय हो गया।", ro:"chalo sone ka samay ho gaya.", en:"Come, it's time to sleep."},
    {sp:"A", hi:"क्या तुम मुझे कहानी सुनाओगी?", ro:"kya tum mujhe kahaani sunaaogi?", en:"Will you tell me a story?"},
    {sp:"B", hi:"हाँ, ज़रूर।", ro:"haan, zaroor.", en:"Yes, of course."},
    {sp:"A", hi:"शुभ रात्रि!", ro:"shubh raatri!", en:"Good night!"},
  ]},
  { id:"c7", name:"Helping Mom", emoji:"🤝", lines:[
    {sp:"A", hi:"माँ, क्या मैं मदद करूँ?", ro:"maa, kya main madad karoon?", en:"Mom, shall I help?"},
    {sp:"B", hi:"हाँ, कृपया मेज़ साफ़ करो।", ro:"haan, kripya mez saaf karo.", en:"Yes, please clean the table."},
    {sp:"A", hi:"ठीक है, हो गया।", ro:"theek hai, ho gaya.", en:"Okay, it's done."},
    {sp:"B", hi:"शाबाश! तुम बहुत अच्छी हो।", ro:"shaabaash! tum bahut achhi ho.", en:"Well done! You are very good."},
    {sp:"A", hi:"धन्यवाद, माँ!", ro:"dhanyavaad, maa!", en:"Thank you, Mom!"},
  ]},
  { id:"c8", name:"What's Your Favorite?", emoji:"❤️", lines:[
    {sp:"A", hi:"तुम्हारा पसंदीदा रंग कौन सा है?", ro:"tumhara pasandeeda rang kaun sa hai?", en:"What is your favorite color?"},
    {sp:"B", hi:"मुझे गुलाबी रंग पसंद है।", ro:"mujhe gulaabi rang pasand hai.", en:"I like the color pink."},
    {sp:"A", hi:"तुम्हारा पसंदीदा फल क्या है?", ro:"tumhara pasandeeda phal kya hai?", en:"What is your favorite fruit?"},
    {sp:"B", hi:"मुझे आम बहुत पसंद हैं।", ro:"mujhe aam bahut pasand hain.", en:"I really like mangoes."},
    {sp:"A", hi:"मुझे भी!", ro:"mujhe bhi!", en:"Me too!"},
  ]},
  { id:"c9", name:"Feeling Sick", emoji:"🤒", lines:[
    {sp:"A", hi:"मेरी तबीयत ठीक नहीं है।", ro:"meri tabiyat theek nahin hai.", en:"I am not feeling well."},
    {sp:"B", hi:"क्या हुआ? कहाँ दर्द है?", ro:"kya hua? kahaan dard hai?", en:"What happened? Where does it hurt?"},
    {sp:"A", hi:"मेरे सिर में दर्द है।", ro:"mere sir mein dard hai.", en:"My head hurts."},
    {sp:"B", hi:"आराम करो, सब ठीक हो जाएगा।", ro:"aaraam karo, sab theek ho jaayega.", en:"Rest, everything will be fine."},
    {sp:"A", hi:"शुक्रिया।", ro:"shukriya.", en:"Thank you."},
  ]},
  { id:"c10", name:"At the Market", emoji:"🛒", lines:[
    {sp:"A", hi:"हमें क्या खरीदना है?", ro:"hamein kya khareedna hai?", en:"What do we need to buy?"},
    {sp:"B", hi:"हमें सेब और दूध चाहिए।", ro:"hamein seb aur doodh chahiye.", en:"We need apples and milk."},
    {sp:"A", hi:"यह कितने का है?", ro:"yeh kitne ka hai?", en:"How much is this?"},
    {sp:"B", hi:"यह बीस रुपये का है।", ro:"yeh bees rupaye ka hai.", en:"This is twenty rupees."},
    {sp:"A", hi:"ठीक है, हम इसे लेंगे।", ro:"theek hai, hum ise lenge.", en:"Okay, we'll take it."},
  ]},
];

if (typeof window !== "undefined") { window.UNITS = UNITS; window.CONVOS = CONVOS; }
