/* Aria's Hindi Garden — content pack (640 words, 20 topics) */

const UNITS = [
  { id:"greet", name:"Hello & Manners", emoji:"👋", words:[
    {hi:"नमस्ते", ro:"namaste", en:"Hello / Goodbye", ic:"🙏"},
    {hi:"बाय", ro:"bye", en:"Goodbye", ic:"👋"},
    {hi:"गुड मॉर्निंग", ro:"good morning", en:"Good morning", ic:"🌅"},
    {hi:"थैंक्यू", ro:"thank you", en:"Thank you", ic:"🙏"},
    {hi:"प्लीज़", ro:"please", en:"Please", ic:"🙏"},
    {hi:"सॉरी", ro:"sorry", en:"Sorry", ic:"😔"},
    {hi:"माफ़ करना", ro:"maaf karna", en:"Excuse me / Forgive me", ic:"🙇"},
    {hi:"वेलकम", ro:"welcome", en:"Welcome", ic:"🤗"},
    {hi:"आप कैसे हो?", ro:"aap kaise ho?", en:"How are you?", ic:"🙂"},
    {hi:"मैं ठीक हूँ", ro:"main theek hoon", en:"I am fine", ic:"👍"},
    {hi:"कोई बात नहीं", ro:"koi baat nahi", en:"No problem / It's okay", ic:"👌"},
    {hi:"चलो", ro:"chalo", en:"Let's go", ic:"🚶"},
    {hi:"अच्छा", ro:"achha", en:"Okay / Good", ic:"👍"},
    {hi:"सुनो", ro:"suno", en:"Listen", ic:"👂"},
    {hi:"शाबाश", ro:"shabaash", en:"Well done", ic:"👏"},
    {hi:"बधाई", ro:"badhaai", en:"Congratulations", ic:"🎉"},
    {hi:"ख्याल रखना", ro:"khayal rakhna", en:"Take care", ic:"🫶"},
    {hi:"फिर मिलेंगे", ro:"phir milenge", en:"See you later", ic:"👋"},
    {hi:"अलविदा", ro:"alvida", en:"Farewell", ic:"🫡"},
    {hi:"कृपया", ro:"kripya", en:"Please (Formal)", ic:"🙏"},
    {hi:"आपका नाम क्या है?", ro:"aapka naam kya hai?", en:"What is your name?", ic:"❓"},
    {hi:"मेरा नाम ___ है", ro:"mera naam ___ hai", en:"My name is ___", ic:"🪪"},
    {hi:"हाथ मिलाओ", ro:"haath milao", en:"Shake hands", ic:"🤝"},
    {hi:"गले लगो", ro:"gale lago", en:"Hug", ic:"🫂"},
    {hi:"आशीर्वाद", ro:"aashirwaad", en:"Blessings", ic:"🙏"},
    {hi:"ध्यान से", ro:"dhyaan se", en:"Carefully", ic:"⚠️"},
    {hi:"धन्यवाद", ro:"dhanyavaad", en:"Thank you (Kept for recognition)", ic:"🙏"},
    {hi:"शुक्रिया", ro:"shukriya", en:"Thank you (Urdu origin)", ic:"🙏"},
    {hi:"एक्सक्यूज़ मी", ro:"excuse me", en:"Excuse me", ic:"🙇"},
    {hi:"ठीक है", ro:"theek hai", en:"All right / Okay", ic:"👌"},
  ]},
  { id:"family", name:"My Family", emoji:"👪", words:[
    {hi:"मम्मी", ro:"mummy", en:"Mom", ic:"👩"},
    {hi:"पापा", ro:"papa", en:"Dad", ic:"👨"},
    {hi:"भाई", ro:"bhai", en:"Brother", ic:"👦"},
    {hi:"बहन", ro:"behen", en:"Sister", ic:"👧"},
    {hi:"दादा", ro:"dada", en:"Paternal Grandfather", ic:"👴"},
    {hi:"दादी", ro:"dadi", en:"Paternal Grandmother", ic:"👵"},
    {hi:"नाना", ro:"nana", en:"Maternal Grandfather", ic:"👴"},
    {hi:"नानी", ro:"nani", en:"Maternal Grandmother", ic:"👵"},
    {hi:"चाचा", ro:"chacha", en:"Paternal Uncle", ic:"🧔"},
    {hi:"चाची", ro:"chachi", en:"Paternal Aunt", ic:"👩"},
    {hi:"बुआ", ro:"bua", en:"Paternal Aunt (Dad's sister)", ic:"👩"},
    {hi:"फूफा", ro:"fufa", en:"Bua's husband", ic:"🧔"},
    {hi:"मामा", ro:"mama", en:"Maternal Uncle", ic:"🧔"},
    {hi:"मामी", ro:"mami", en:"Maternal Aunt", ic:"👩"},
    {hi:"मौसी", ro:"mausi", en:"Maternal Aunt (Mom's sister)", ic:"👩"},
    {hi:"मौसा", ro:"mausa", en:"Mausi's husband", ic:"🧔"},
    {hi:"बेटा", ro:"beta", en:"Son / Child", ic:"👦"},
    {hi:"बेटी", ro:"beti", en:"Daughter", ic:"👧"},
    {hi:"परिवार", ro:"parivaar", en:"Family", ic:"👨‍👩‍👧‍👦"},
    {hi:"रिश्तेदार", ro:"rishtedaar", en:"Relatives", ic:"👪"},
    {hi:"दोस्त", ro:"dost", en:"Friend", ic:"🧑‍🤝‍🧑"},
    {hi:"पड़ोसी", ro:"padosi", en:"Neighbor", ic:"🏘️"},
    {hi:"मेहमान", ro:"mehmaan", en:"Guest", ic:"🧳"},
    {hi:"बड़ा भाई", ro:"bada bhai", en:"Elder brother", ic:"🧑"},
    {hi:"छोटी बहन", ro:"chhoti behen", en:"Younger sister", ic:"👧"},
    {hi:"जुड़वाँ", ro:"judwa", en:"Twins", ic:"👯"},
    {hi:"भाभी", ro:"bhabhi", en:"Brother's wife", ic:"👰"},
    {hi:"जीजा", ro:"jija", en:"Sister's husband", ic:"🤵"},
    {hi:"ताया", ro:"taya", en:"Older Paternal Uncle", ic:"🧔"},
    {hi:"ताई", ro:"tayi", en:"Taya's wife", ic:"👩"},
    {hi:"अंकल", ro:"uncle", en:"Uncle (General)", ic:"🧔"},
    {hi:"आंटी", ro:"aunty", en:"Aunt (General)", ic:"👩"},
  ]},
  { id:"feel", name:"Feelings & States", emoji:"😊", words:[
    {hi:"खुश", ro:"khush", en:"Happy", ic:"😄"},
    {hi:"उदास", ro:"udaas", en:"Sad", ic:"😢"},
    {hi:"गुस्सा", ro:"gussa", en:"Angry", ic:"😠"},
    {hi:"डर", ro:"dar", en:"Fear / Scared", ic:"😨"},
    {hi:"थका हुआ", ro:"thaka hua", en:"Tired", ic:"🥱"},
    {hi:"भूखा", ro:"bhookha", en:"Hungry", ic:"🍽️"},
    {hi:"प्यासा", ro:"pyaasa", en:"Thirsty", ic:"🥤"},
    {hi:"नींद", ro:"neend", en:"Sleepy / Sleep", ic:"😴"},
    {hi:"बीमार", ro:"bimaar", en:"Sick", ic:"🤒"},
    {hi:"ठीक", ro:"theek", en:"Fine / Okay", ic:"🙂"},
    {hi:"दर्द", ro:"dard", en:"Pain", ic:"🤕"},
    {hi:"गरम", ro:"garam", en:"Hot (Feeling)", ic:"🥵"},
    {hi:"ठंडा", ro:"thanda", en:"Cold (Feeling)", ic:"🥶"},
    {hi:"परेशान", ro:"pareshan", en:"Worried / Bothered", ic:"😟"},
    {hi:"हैरान", ro:"hairaan", en:"Surprised", ic:"😲"},
    {hi:"बोर", ro:"bore", en:"Bored", ic:"😑"},
    {hi:"एक्साइटेड", ro:"excited", en:"Excited", ic:"🤩"},
    {hi:"रोना", ro:"rona", en:"To cry / Crying", ic:"😭"},
    {hi:"हँसना", ro:"hansna", en:"To laugh / Laughing", ic:"😂"},
    {hi:"मुस्कुराना", ro:"muskurana", en:"To smile", ic:"😊"},
    {hi:"शर्माना", ro:"sharmaana", en:"To be shy", ic:"😳"},
    {hi:"चिंता", ro:"chinta", en:"Worry", ic:"😟"},
    {hi:"शांति", ro:"shanti", en:"Peace / Calm", ic:"😌"},
    {hi:"अकेला", ro:"akela", en:"Alone", ic:"🧍"},
    {hi:"साथ", ro:"saath", en:"Together", ic:"🤝"},
    {hi:"प्यार", ro:"pyar", en:"Love", ic:"❤️"},
    {hi:"नफरत", ro:"nafrat", en:"Hate", ic:"💢"},
    {hi:"पसंद", ro:"pasand", en:"Like", ic:"👍"},
    {hi:"नापसंद", ro:"na-pasand", en:"Dislike", ic:"👎"},
    {hi:"घबराहट", ro:"ghabrahat", en:"Nervousness", ic:"😰"},
    {hi:"आलसी", ro:"aalsi", en:"Lazy", ic:"🦥"},
  ]},
  { id:"num", name:"Numbers", emoji:"🔢", words:[
    {hi:"एक", ro:"ek", en:"One", ic:"1️⃣"},
    {hi:"दो", ro:"do", en:"Two", ic:"2️⃣"},
    {hi:"तीन", ro:"teen", en:"Three", ic:"3️⃣"},
    {hi:"चार", ro:"chaar", en:"Four", ic:"4️⃣"},
    {hi:"पांच", ro:"paanch", en:"Five", ic:"5️⃣"},
    {hi:"छह", ro:"chhe", en:"Six", ic:"6️⃣"},
    {hi:"सात", ro:"saat", en:"Seven", ic:"7️⃣"},
    {hi:"आठ", ro:"aath", en:"Eight", ic:"8️⃣"},
    {hi:"नौ", ro:"nau", en:"Nine", ic:"9️⃣"},
    {hi:"दस", ro:"dus", en:"Ten", ic:"🔟"},
    {hi:"ग्यारह", ro:"gyaarah", en:"Eleven", ic:"11"},
    {hi:"बारह", ro:"baarah", en:"Twelve", ic:"12"},
    {hi:"तेरह", ro:"terah", en:"Thirteen", ic:"13"},
    {hi:"चौदह", ro:"chaudah", en:"Fourteen", ic:"14"},
    {hi:"पंद्रह", ro:"pandrah", en:"Fifteen", ic:"15"},
    {hi:"सोलह", ro:"solah", en:"Sixteen", ic:"16"},
    {hi:"सत्रह", ro:"satrah", en:"Seventeen", ic:"17"},
    {hi:"अट्ठारह", ro:"atharah", en:"Eighteen", ic:"18"},
    {hi:"उन्नीस", ro:"unnis", en:"Nineteen", ic:"19"},
    {hi:"बीस", ro:"bees", en:"Twenty", ic:"20"},
    {hi:"पच्चीस", ro:"pachees", en:"Twenty-five", ic:"25"},
    {hi:"तीस", ro:"tees", en:"Thirty", ic:"30"},
    {hi:"चालीस", ro:"chalees", en:"Forty", ic:"40"},
    {hi:"पचास", ro:"pachaas", en:"Fifty", ic:"50"},
    {hi:"साठ", ro:"saath", en:"Sixty", ic:"60"},
    {hi:"सत्तर", ro:"sattar", en:"Seventy", ic:"70"},
    {hi:"अस्सी", ro:"assi", en:"Eighty", ic:"80"},
    {hi:"नब्बे", ro:"nabbe", en:"Ninety", ic:"90"},
    {hi:"सौ", ro:"sau", en:"Hundred", ic:"100"},
    {hi:"हज़ार", ro:"hazaar", en:"Thousand", ic:"1000"},
    {hi:"लाख", ro:"laakh", en:"Hundred Thousand", ic:"100000"},
    {hi:"जीरो / शून्य", ro:"zero / Shoonya", en:"Zero", ic:"0️⃣"},
    {hi:"आधा", ro:"aadha", en:"Half", ic:"½"},
    {hi:"पहला", ro:"pehla", en:"First", ic:"1st"},
    {hi:"दूसरा", ro:"doosra", en:"Second", ic:"2nd"},
  ]},
  { id:"color", name:"Colors", emoji:"🎨", words:[
    {hi:"लाल", ro:"laal", en:"Red", ic:"🔴"},
    {hi:"नीला", ro:"neela", en:"Blue", ic:"🔵"},
    {hi:"पीला", ro:"peela", en:"Yellow", ic:"🟡"},
    {hi:"हरा", ro:"hara", en:"Green", ic:"🟢"},
    {hi:"काला", ro:"kaala", en:"Black", ic:"⚫"},
    {hi:"सफ़ेद", ro:"safed", en:"White", ic:"⚪"},
    {hi:"गुलाबी", ro:"gulaabi", en:"Pink", ic:"🩷"},
    {hi:"नारंगी / संतरी", ro:"narangi / Santree", en:"Orange", ic:"🍊"},
    {hi:"भूरा", ro:"bhura", en:"Brown", ic:"🟤"},
    {hi:"बैंगनी", ro:"baingani", en:"Purple", ic:"🟣"},
    {hi:"सुनहरा", ro:"sunehra", en:"Golden", ic:"🥇"},
    {hi:"चांदी", ro:"chaandi", en:"Silver", ic:"🥈"},
    {hi:"हल्का", ro:"halka", en:"Light (color)", ic:"🤍"},
    {hi:"गाढ़ा", ro:"gaadha", en:"Dark (color)", ic:"🖤"},
    {hi:"रंग", ro:"rang", en:"Color", ic:"🎨"},
    {hi:"चमकीला", ro:"chamkeela", en:"Bright / Shiny", ic:"✨"},
    {hi:"फीका", ro:"feeka", en:"Dull / Faded", ic:"🌫️"},
    {hi:"स्लेटी", ro:"slety", en:"Grey", ic:"🩶"},
    {hi:"फ़िरोज़ी", ro:"firozi", en:"Turquoise", ic:"🩵"},
    {hi:"आसमानी", ro:"aasmaani", en:"Sky blue", ic:"🟦"},
    {hi:"जामुनी", ro:"jamuni", en:"Plum / Deep Purple", ic:"🍇"},
    {hi:"मेंहदी", ro:"mehndi", en:"Olive green", ic:"🫒"},
    {hi:"सिंदूरी", ro:"sindhoori", en:"Vermillion", ic:"🟥"},
    {hi:"क्रीम", ro:"cream", en:"Cream", ic:"🍦"},
    {hi:"मरून", ro:"maroon", en:"Maroon", ic:"🍷"},
    {hi:"नेवी ब्लू", ro:"navy Blue", en:"Navy Blue", ic:"🔷"},
    {hi:"रंग-बिरंगा", ro:"rang-biranga", en:"Colorful", ic:"🌈"},
    {hi:"गहरा", ro:"gehra", en:"Deep (color)", ic:"🌑"},
    {hi:"गोरा", ro:"gora", en:"Fair (skin tone)", ic:"🫅"},
    {hi:"सांवला", ro:"saanvla", en:"Dusky / Tan", ic:"🟫"},
  ]},
  { id:"animal", name:"Animals", emoji:"🐘", words:[
    {hi:"कुत्ता", ro:"kutta", en:"Dog", ic:"🐶"},
    {hi:"बिल्ली", ro:"billi", en:"Cat", ic:"🐱"},
    {hi:"गाय", ro:"gaay", en:"Cow", ic:"🐮"},
    {hi:"भैंस", ro:"bhains", en:"Buffalo", ic:"🐃"},
    {hi:"बकरी", ro:"bakri", en:"Goat", ic:"🐐"},
    {hi:"भेड़", ro:"bhed", en:"Sheep", ic:"🐑"},
    {hi:"घोड़ा", ro:"ghoda", en:"Horse", ic:"🐴"},
    {hi:"गधा", ro:"gadha", en:"Donkey", ic:"🫏"},
    {hi:"हाथी", ro:"hathi", en:"Elephant", ic:"🐘"},
    {hi:"शेर", ro:"sher", en:"Lion", ic:"🦁"},
    {hi:"बाघ", ro:"baagh", en:"Tiger", ic:"🐯"},
    {hi:"भालू", ro:"bhalu", en:"Bear", ic:"🐻"},
    {hi:"बंदर", ro:"bandar", en:"Monkey", ic:"🐒"},
    {hi:"हिरन", ro:"hiran", en:"Deer", ic:"🦌"},
    {hi:"चूहा", ro:"chuha", en:"Mouse / Rat", ic:"🐭"},
    {hi:"खरगोश", ro:"khargosh", en:"Rabbit", ic:"🐰"},
    {hi:"कछुआ", ro:"kacchua", en:"Turtle", ic:"🐢"},
    {hi:"मछली", ro:"machhli", en:"Fish", ic:"🐟"},
    {hi:"चिड़िया", ro:"chidiya", en:"Bird", ic:"🐦"},
    {hi:"कौआ", ro:"kauwa", en:"Crow", ic:"🐦‍⬛"},
    {hi:"कबूतर", ro:"kabootar", en:"Pigeon", ic:"🕊️"},
    {hi:"तोता", ro:"tota", en:"Parrot", ic:"🦜"},
    {hi:"मोर", ro:"mor", en:"Peacock", ic:"🦚"},
    {hi:"मुर्गी", ro:"murgi", en:"Hen / Chicken", ic:"🐔"},
    {hi:"कीड़ा", ro:"keeda", en:"Bug / Insect", ic:"🐛"},
    {hi:"मकड़ी", ro:"makdi", en:"Spider", ic:"🕷️"},
    {hi:"मच्छर", ro:"machhar", en:"Mosquito", ic:"🦟"},
    {hi:"मक्खी", ro:"makkhi", en:"Fly", ic:"🪰"},
    {hi:"सांप", ro:"saamp", en:"Snake", ic:"🐍"},
    {hi:"छिपकली", ro:"chhipkali", en:"Lizard", ic:"🦎"},
    {hi:"मेंढक", ro:"mendhak", en:"Frog", ic:"🐸"},
    {hi:"मगरमच्छ", ro:"magarmach", en:"Crocodile", ic:"🐊"},
  ]},
  { id:"food", name:"Food & Drink", emoji:"🍱", words:[
    {hi:"खाना", ro:"khaana", en:"Food / Meal", ic:"🍱"},
    {hi:"पानी", ro:"paani", en:"Water", ic:"💧"},
    {hi:"दूध", ro:"doodh", en:"Milk", ic:"🥛"},
    {hi:"नाश्ता", ro:"naashta", en:"Breakfast / Snack", ic:"🍳"},
    {hi:"लंच", ro:"lunch", en:"Lunch", ic:"🍛"},
    {hi:"डिनर", ro:"dinner", en:"Dinner", ic:"🍽️"},
    {hi:"रोटी", ro:"roti", en:"Flatbread", ic:"🫓"},
    {hi:"चावल", ro:"chaawal", en:"Rice", ic:"🍚"},
    {hi:"दाल", ro:"daal", en:"Lentils", ic:"🍲"},
    {hi:"सब्ज़ी", ro:"sabzi", en:"Cooked vegetable dish", ic:"🥘"},
    {hi:"दही", ro:"dahi", en:"Yogurt / Curd", ic:"🥣"},
    {hi:"पनीर", ro:"paneer", en:"Cottage Cheese", ic:"🧀"},
    {hi:"जूस", ro:"juice", en:"Juice", ic:"🧃"},
    {hi:"चाय", ro:"chai", en:"Tea", ic:"🍵"},
    {hi:"कॉफी", ro:"coffee", en:"Coffee", ic:"☕"},
    {hi:"रायता", ro:"raita", en:"Yogurt dip", ic:"🥣"},
    {hi:"पराठा", ro:"paratha", en:"Stuffed flatbread", ic:"🫓"},
    {hi:"पूरी", ro:"puri", en:"Fried flatbread", ic:"🍩"},
    {hi:"पापड़", ro:"papad", en:"Papadum", ic:"🥠"},
    {hi:"भर्ता", ro:"bharta", en:"Mashed dish", ic:"🥘"},
    {hi:"बिस्कुट", ro:"biscuit", en:"Cookies / Biscuits", ic:"🍪"},
    {hi:"केक", ro:"cake", en:"Cake", ic:"🍰"},
    {hi:"मिठाई", ro:"mithai", en:"Sweets", ic:"🍮"},
    {hi:"समोसा", ro:"samosa", en:"Samosa", ic:"🥟"},
    {hi:"अंडा", ro:"anda", en:"Egg", ic:"🥚"},
    {hi:"मीट", ro:"meat", en:"Meat", ic:"🍖"},
    {hi:"चिकन", ro:"chicken", en:"Chicken", ic:"🍗"},
    {hi:"मक्खन", ro:"makkhan", en:"Butter", ic:"🧈"},
    {hi:"अचार", ro:"achaar", en:"Pickle", ic:"🥒"},
    {hi:"नमक", ro:"namak", en:"Salt", ic:"🧂"},
    {hi:"चीनी", ro:"cheeni", en:"Sugar", ic:"🍬"},
    {hi:"मसाला", ro:"masaala", en:"Spice", ic:"🌶️"},
    {hi:"तेल", ro:"tel", en:"Oil", ic:"🫗"},
    {hi:"घी", ro:"ghee", en:"Clarified Butter", ic:"🧈"},
  ]},
  { id:"fruitveg", name:"Fruits & Veggies", emoji:"🍎", words:[
    {hi:"सेब", ro:"seb", en:"Apple", ic:"🍎"},
    {hi:"केला", ro:"kela", en:"Banana", ic:"🍌"},
    {hi:"आम", ro:"aam", en:"Mango", ic:"🥭"},
    {hi:"संतरा", ro:"santra", en:"Orange", ic:"🍊"},
    {hi:"अंगूर", ro:"angoor", en:"Grapes", ic:"🍇"},
    {hi:"अमरूद", ro:"amrood", en:"Guava", ic:"🍐"},
    {hi:"पपीता", ro:"papita", en:"Papaya", ic:"🫐"},
    {hi:"अनार", ro:"anaar", en:"Pomegranate", ic:"🍎"},
    {hi:"तरबूज", ro:"tarbooz", en:"Watermelon", ic:"🍉"},
    {hi:"खरबूजा", ro:"kharbooza", en:"Cantaloupe / Melon", ic:"🍈"},
    {hi:"नींबू", ro:"nimbu", en:"Lemon", ic:"🍋"},
    {hi:"नारियल", ro:"nariyal", en:"Coconut", ic:"🥥"},
    {hi:"आलू", ro:"aloo", en:"Potato", ic:"🥔"},
    {hi:"प्याज़", ro:"pyaaz", en:"Onion", ic:"🧅"},
    {hi:"टमाटर", ro:"tamatar", en:"Tomato", ic:"🍅"},
    {hi:"भिंडी", ro:"bhindi", en:"Okra", ic:"🫛"},
    {hi:"करेला", ro:"karela", en:"Bitter Gourd", ic:"🥒"},
    {hi:"कद्दू", ro:"kaddu", en:"Pumpkin", ic:"🎃"},
    {hi:"गाजर", ro:"gajar", en:"Carrot", ic:"🥕"},
    {hi:"मूली", ro:"mooli", en:"Radish", ic:"🌱"},
    {hi:"पालक", ro:"palak", en:"Spinach", ic:"🥬"},
    {hi:"गोभी", ro:"gobhi", en:"Cauliflower", ic:"🥦"},
    {hi:"पत्ता गोभी", ro:"patta Gobhi", en:"Cabbage", ic:"🥬"},
    {hi:"मटर", ro:"matar", en:"Peas", ic:"🫛"},
    {hi:"बैंगन", ro:"baingan", en:"Eggplant", ic:"🍆"},
    {hi:"शिमला मिर्च", ro:"shimla Mirch", en:"Capsicum / Bell Pepper", ic:"🫑"},
    {hi:"लहसुन", ro:"lahsun", en:"Garlic", ic:"🧄"},
    {hi:"अदरक", ro:"adrak", en:"Ginger", ic:"🫚"},
    {hi:"हरी मिर्च", ro:"hari Mirch", en:"Green Chili", ic:"🌶️"},
    {hi:"धनिया", ro:"dhania", en:"Coriander / Cilantro", ic:"🌿"},
    {hi:"पुदीना", ro:"pudina", en:"Mint", ic:"🌿"},
    {hi:"खीरा", ro:"kheera", en:"Cucumber", ic:"🥒"},
  ]},
  { id:"body", name:"My Body", emoji:"🧍", words:[
    {hi:"हाथ", ro:"haath", en:"Hand / Arm", ic:"✋"},
    {hi:"पैर", ro:"pair", en:"Foot / Leg", ic:"🦶"},
    {hi:"सिर", ro:"sir", en:"Head", ic:"👤"},
    {hi:"बाल", ro:"baal", en:"Hair", ic:"💇"},
    {hi:"आँख", ro:"aankh", en:"Eye", ic:"👁️"},
    {hi:"कान", ro:"kaan", en:"Ear", ic:"👂"},
    {hi:"नाक", ro:"naak", en:"Nose", ic:"👃"},
    {hi:"मुँह", ro:"munh", en:"Mouth", ic:"👄"},
    {hi:"दाँत", ro:"daant", en:"Tooth / Teeth", ic:"🦷"},
    {hi:"जीभ", ro:"jeebh", en:"Tongue", ic:"👅"},
    {hi:"पेट", ro:"pet", en:"Stomach", ic:"🫃"},
    {hi:"पीठ", ro:"peeth", en:"Back", ic:"🧍"},
    {hi:"उंगली", ro:"ungli", en:"Finger", ic:"👆"},
    {hi:"अंगूठा", ro:"angootha", en:"Thumb", ic:"👍"},
    {hi:"गर्दन", ro:"gardan", en:"Neck", ic:"🧣"},
    {hi:"कंधा", ro:"kandha", en:"Shoulder", ic:"💪"},
    {hi:"सीना", ro:"seena", en:"Chest", ic:"🫁"},
    {hi:"गाल", ro:"gaal", en:"Cheek", ic:"😊"},
    {hi:"होंठ", ro:"honth", en:"Lips", ic:"💋"},
    {hi:"माथा", ro:"maatha", en:"Forehead", ic:"😯"},
    {hi:"घुटना", ro:"ghutna", en:"Knee", ic:"🦵"},
    {hi:"टखना", ro:"takhna", en:"Ankle", ic:"🦶"},
    {hi:"नाखून", ro:"naakhun", en:"Nail", ic:"💅"},
    {hi:"चमड़ी", ro:"chamdi", en:"Skin", ic:"🤲"},
    {hi:"खून", ro:"khoon", en:"Blood", ic:"🩸"},
    {hi:"हड्डी", ro:"haddee", en:"Bone", ic:"🦴"},
    {hi:"दिल", ro:"dil", en:"Heart", ic:"❤️"},
    {hi:"दिमाग", ro:"dimaag", en:"Brain", ic:"🧠"},
    {hi:"आँसू", ro:"aansu", en:"Tears", ic:"😢"},
    {hi:"पसीना", ro:"paseena", en:"Sweat", ic:"💦"},
    {hi:"साँस", ro:"saans", en:"Breath", ic:"😮‍💨"},
  ]},
  { id:"phrase", name:"Everyday Phrases", emoji:"💬", words:[
    {hi:"अरे यार", ro:"arey yaar", en:"Oh man!", ic:"😩"},
    {hi:"क्या हुआ?", ro:"kya hua?", en:"What happened?", ic:"😯"},
    {hi:"मुझे नहीं पता", ro:"mujhe nahi pata", en:"I don't know", ic:"🤷"},
    {hi:"पक्का?", ro:"pakka?", en:"Are you sure?", ic:"🤨"},
    {hi:"बस करो", ro:"bas karo", en:"Stop it / Enough", ic:"✋"},
    {hi:"मुझे भूख लगी है", ro:"mujhe bhookh lagi hai", en:"I am hungry", ic:"🍽️"},
    {hi:"मुझे प्यास लगी है", ro:"mujhe pyaas lagi hai", en:"I am thirsty", ic:"🥤"},
    {hi:"मुझे नींद आ रही है", ro:"mujhe neend aa rahi hai", en:"I am sleepy", ic:"😴"},
    {hi:"टीवी चला दो", ro:"tV chala do", en:"Turn on the TV", ic:"📺"},
    {hi:"लाइट बंद करो", ro:"light band karo", en:"Turn off the light", ic:"💡"},
    {hi:"आओ खेलें", ro:"aao khelein", en:"Let's play", ic:"🎮"},
    {hi:"मैं जा रही हूँ", ro:"main ja rahi hoon", en:"I am going", ic:"🚶"},
    {hi:"क्या मैं टीवी देख सकती हूँ?", ro:"kya main TV dekh sakti hoon?", en:"Can I watch TV?", ic:"📺"},
    {hi:"यह क्या है?", ro:"yeh kya hai?", en:"What is this?", ic:"❓"},
    {hi:"वह क्या है?", ro:"woh kya hai?", en:"What is that?", ic:"❔"},
    {hi:"कहाँ जा रहे हो?", ro:"kahan ja rahe ho?", en:"Where are you going?", ic:"🧭"},
    {hi:"जल्दी आओ", ro:"jaldi aao", en:"Come quickly", ic:"🏃"},
    {hi:"देर हो रही है", ro:"der ho rahi hai", en:"It's getting late", ic:"⏰"},
    {hi:"मुझे पसंद है", ro:"mujhe pasand hai", en:"I like it", ic:"👍"},
    {hi:"मुझे पसंद नहीं है", ro:"mujhe pasand nahi hai", en:"I don't like it", ic:"👎"},
    {hi:"मदद करो", ro:"madad karo", en:"Help me", ic:"🆘"},
    {hi:"चोट लग गई", ro:"chot lag gayi", en:"I got hurt", ic:"🤕"},
    {hi:"फ़ोन कहाँ है?", ro:"phone kahan hai?", en:"Where is the phone?", ic:"📱"},
    {hi:"एसी चला दो", ro:"aC chala do", en:"Turn on the AC", ic:"❄️"},
    {hi:"चुप रहो", ro:"chup raho", en:"Be quiet", ic:"🤫"},
    {hi:"शोर मत मचाओ", ro:"shor mat machao", en:"Don't make noise", ic:"🔇"},
    {hi:"ध्यान से", ro:"dhyaan se", en:"Be careful", ic:"⚠️"},
    {hi:"जाने दो", ro:"jaane do", en:"Let it go", ic:"🤚"},
    {hi:"कोई बात नहीं", ro:"koi baat nahi", en:"Never mind", ic:"🙄"},
    {hi:"तैयार हो जाओ", ro:"taiyaar ho jao", en:"Get ready", ic:"🎒"},
    {hi:"मैं भूल गई", ro:"main bhool gayi", en:"I forgot", ic:"🤦"},
  ]},
  { id:"ask", name:"Asking & Wanting", emoji:"🙋", words:[
    {hi:"चाहिए", ro:"chahiye", en:"Want / Need", ic:"🙏"},
    {hi:"माँगना", ro:"maangna", en:"To ask for / Request", ic:"🙋"},
    {hi:"देना", ro:"dena", en:"To give", ic:"🤲"},
    {hi:"लेना", ro:"lena", en:"To take", ic:"🫳"},
    {hi:"क्या?", ro:"kya?", en:"What?", ic:"❓"},
    {hi:"क्यों?", ro:"kyon?", en:"Why?", ic:"❓"},
    {hi:"कहाँ?", ro:"kahan?", en:"Where?", ic:"📍"},
    {hi:"कब?", ro:"kab?", en:"When?", ic:"🕐"},
    {hi:"कैसे?", ro:"kaise?", en:"How?", ic:"❓"},
    {hi:"कौन?", ro:"kaun?", en:"Who?", ic:"👤"},
    {hi:"किसका?", ro:"kiska?", en:"Whose?", ic:"🧐"},
    {hi:"कितना?", ro:"kitna?", en:"How much / How many?", ic:"🔢"},
    {hi:"मुझे दो", ro:"mujhe do", en:"Give me", ic:"🤲"},
    {hi:"क्या मैं लूँ?", ro:"kya main loon?", en:"Can I take?", ic:"✋"},
    {hi:"क्या मैं करूँ?", ro:"kya main karoon?", en:"Should I do it?", ic:"🤔"},
    {hi:"क्या मैं जाऊँ?", ro:"kya main jaaun?", en:"Should I go?", ic:"🚶"},
    {hi:"पूछो", ro:"poocho", en:"Ask", ic:"🙋"},
    {hi:"जवाब दो", ro:"jawaab do", en:"Answer", ic:"💬"},
    {hi:"सवाल", ro:"sawaal", en:"Question", ic:"❓"},
    {hi:"मदद", ro:"madad", en:"Help", ic:"🆘"},
    {hi:"मुझे चाहिए", ro:"mujhe chahiye", en:"I want / I need", ic:"🙋"},
    {hi:"और चाहिए", ro:"aur chahiye", en:"Want more", ic:"➕"},
    {hi:"एक और", ro:"ek aur", en:"One more", ic:"🔂"},
    {hi:"थोड़ा सा", ro:"thoda sa", en:"A little bit", ic:"🤏"},
    {hi:"ज़्यादा", ro:"zyada", en:"More / A lot", ic:"➕"},
    {hi:"कम", ro:"kam", en:"Less", ic:"➖"},
    {hi:"किसलिए?", ro:"kislie?", en:"For what?", ic:"❓"},
    {hi:"किसको?", ro:"kisko?", en:"To whom?", ic:"👉"},
    {hi:"कौन सा?", ro:"kaun sa?", en:"Which one?", ic:"👆"},
    {hi:"प्लीज़ दे दो", ro:"please de do", en:"Please give it", ic:"🙏"},
    {hi:"मैं लूँ?", ro:"main loon?", en:"May I take?", ic:"✋"},
  ]},
  { id:"day", name:"My Day & Routine", emoji:"🌞", words:[
    {hi:"सुबह", ro:"subah", en:"Morning", ic:"🌅"},
    {hi:"दोपहर", ro:"dopahar", en:"Afternoon", ic:"☀️"},
    {hi:"शाम", ro:"shaam", en:"Evening", ic:"🌇"},
    {hi:"रात", ro:"raat", en:"Night", ic:"🌙"},
    {hi:"उठना", ro:"uthna", en:"To wake up", ic:"⏰"},
    {hi:"ब्रश करना", ro:"brush karna", en:"To brush teeth", ic:"🪥"},
    {hi:"नहाना", ro:"nahana", en:"To take a bath/shower", ic:"🚿"},
    {hi:"तैयार होना", ro:"taiyaar hona", en:"To get ready", ic:"🎒"},
    {hi:"नाश्ता करना", ro:"naashta karna", en:"To eat breakfast", ic:"🍳"},
    {hi:"स्कूल जाना", ro:"school jaana", en:"To go to school", ic:"🏫"},
    {hi:"पढ़ना", ro:"padhna", en:"To study/read", ic:"📚"},
    {hi:"खेलना", ro:"khelna", en:"To play", ic:"⚽"},
    {hi:"होमवर्क", ro:"homework", en:"Homework", ic:"📝"},
    {hi:"टीवी देखना", ro:"tV dekhna", en:"To watch TV", ic:"📺"},
    {hi:"डिनर करना", ro:"dinner karna", en:"To eat dinner", ic:"🍽️"},
    {hi:"सोना", ro:"sona", en:"To sleep", ic:"😴"},
    {hi:"दिन", ro:"din", en:"Day", ic:"📅"},
    {hi:"आज", ro:"aaj", en:"Today", ic:"📆"},
    {hi:"कल", ro:"kal", en:"Tomorrow / Yesterday", ic:"🗓️"},
    {hi:"परसों", ro:"parson", en:"Day after tomorrow / Day before yesterday", ic:"🗓️"},
    {hi:"रोज़", ro:"roz", en:"Daily / Everyday", ic:"🔁"},
    {hi:"कभी-कभी", ro:"kabhi-kabhi", en:"Sometimes", ic:"🤷"},
    {hi:"हमेशा", ro:"hamesha", en:"Always", ic:"♾️"},
    {hi:"टाइम", ro:"time", en:"Time", ic:"⏰"},
    {hi:"बजे", ro:"baje", en:"O'clock", ic:"🕐"},
    {hi:"जल्दी", ro:"jaldi", en:"Early / Fast", ic:"⚡"},
    {hi:"देर", ro:"der", en:"Late", ic:"🐢"},
    {hi:"आराम करना", ro:"aaram karna", en:"To rest", ic:"🛋️"},
    {hi:"मुँह धोना", ro:"munh dhona", en:"To wash face", ic:"🧼"},
    {hi:"कपड़े बदलना", ro:"kapde badalna", en:"To change clothes", ic:"👕"},
  ]},
  { id:"home", name:"Home & Rooms", emoji:"🏠", words:[
    {hi:"घर", ro:"ghar", en:"House / Home", ic:"🏠"},
    {hi:"कमरा", ro:"kamra", en:"Room", ic:"🚪"},
    {hi:"रसोई", ro:"rasoi", en:"Kitchen", ic:"🍳"},
    {hi:"बाथरूम", ro:"bathroom", en:"Bathroom / Washroom", ic:"🚿"},
    {hi:"टॉयलेट", ro:"toilet", en:"Toilet", ic:"🚽"},
    {hi:"बिस्तर", ro:"bistar", en:"Bed", ic:"🛏️"},
    {hi:"तकिया", ro:"takiya", en:"Pillow", ic:"🛌"},
    {hi:"कम्बल", ro:"kambal", en:"Blanket", ic:"🧶"},
    {hi:"अलमारी", ro:"almaari", en:"Closet / Wardrobe", ic:"🗄️"},
    {hi:"खिलौने", ro:"khilaune", en:"Toys", ic:"🧸"},
    {hi:"कूड़ा", ro:"kooda", en:"Trash / Garbage", ic:"🗑️"},
    {hi:"डस्टबिन", ro:"dustbin", en:"Trash can", ic:"🗑️"},
    {hi:"लाइट", ro:"light", en:"Light", ic:"💡"},
    {hi:"पंखा", ro:"pankha", en:"Fan", ic:"🌀"},
    {hi:"दरवाज़ा", ro:"darwaza", en:"Door", ic:"🚪"},
    {hi:"खिड़की", ro:"khidki", en:"Window", ic:"🪟"},
    {hi:"चाबी", ro:"chaabi", en:"Key", ic:"🔑"},
    {hi:"आँगन", ro:"aangan", en:"Backyard / Courtyard", ic:"🏡"},
    {hi:"छत", ro:"chhat", en:"Roof / Ceiling", ic:"🏠"},
    {hi:"फ़र्श", ro:"farsh", en:"Floor", ic:"⬜"},
    {hi:"दीवार", ro:"deewar", en:"Wall", ic:"🧱"},
    {hi:"सीढ़ियां", ro:"seedhiyan", en:"Stairs", ic:"🪜"},
    {hi:"सोफ़ा", ro:"sofa", en:"Sofa / Couch", ic:"🛋️"},
    {hi:"टीवी", ro:"tV", en:"Television", ic:"📺"},
    {hi:"फ़्रिज", ro:"fridge", en:"Refrigerator", ic:"🧊"},
    {hi:"वाशिंग मशीन", ro:"washing machine", en:"Washing machine", ic:"🧺"},
    {hi:"टोटी", ro:"toti", en:"Tap / Faucet", ic:"🚰"},
    {hi:"साबुन", ro:"sabun", en:"Soap", ic:"🧼"},
    {hi:"तौलिया", ro:"tauliya", en:"Towel", ic:"🧻"},
    {hi:"शीशा", ro:"sheesha", en:"Mirror / Glass", ic:"🪞"},
    {hi:"कालीन", ro:"kaaleen", en:"Carpet / Rug", ic:"🟫"},
  ]},
  { id:"clothes", name:"Clothes", emoji:"👕", words:[
    {hi:"कपड़े", ro:"kapde", en:"Clothes", ic:"👕"},
    {hi:"जूते", ro:"joote", en:"Shoes", ic:"👟"},
    {hi:"मोजे", ro:"moje", en:"Socks", ic:"🧦"},
    {hi:"चप्पल", ro:"chappal", en:"Slippers / Flip-flops", ic:"🩴"},
    {hi:"टोपी", ro:"topi", en:"Hat / Cap", ic:"🧢"},
    {hi:"जैकेट", ro:"jacket", en:"Jacket / Coat", ic:"🧥"},
    {hi:"रूमाल", ro:"rumaal", en:"Handkerchief", ic:"🧻"},
    {hi:"कमीज़", ro:"kameez", en:"Shirt", ic:"👔"},
    {hi:"पेंट", ro:"pant", en:"Pants", ic:"👖"},
    {hi:"टी-शर्ट", ro:"t-shirt", en:"T-shirt", ic:"👕"},
    {hi:"फ्रॉक", ro:"frock", en:"Dress / Frock", ic:"👗"},
    {hi:"स्कर्ट", ro:"skirt", en:"Skirt", ic:"🩱"},
    {hi:"सूट", ro:"suit", en:"Suit", ic:"🤵"},
    {hi:"कुर्ता", ro:"kurta", en:"Kurta", ic:"👘"},
    {hi:"पजामा", ro:"pajama", en:"Pajamas", ic:"🩳"},
    {hi:"दुपट्टा", ro:"dupatta", en:"Scarf / Dupatta", ic:"🧣"},
    {hi:"साड़ी", ro:"saree", en:"Saree", ic:"🥻"},
    {hi:"स्वेटर", ro:"sweater", en:"Sweater", ic:"🧶"},
    {hi:"मफ़लर", ro:"muffler", en:"Muffler / Scarf", ic:"🧣"},
    {hi:"दस्ताने", ro:"dastaane", en:"Gloves", ic:"🧤"},
    {hi:"बेल्ट", ro:"belt", en:"Belt", ic:"🪢"},
    {hi:"चश्मा", ro:"chashma", en:"Glasses / Sunglasses", ic:"🕶️"},
    {hi:"घड़ी", ro:"ghadi", en:"Watch", ic:"⌚"},
    {hi:"चेन", ro:"chain", en:"Necklace / Chain", ic:"📿"},
    {hi:"बाली", ro:"baali", en:"Earrings", ic:"💎"},
    {hi:"जूती", ro:"jooti", en:"Traditional shoes", ic:"🥿"},
    {hi:"बटन", ro:"button", en:"Button", ic:"🔘"},
    {hi:"ज़िप", ro:"zip", en:"Zipper", ic:"🧷"},
    {hi:"पहनना", ro:"pehnna", en:"To wear", ic:"👕"},
    {hi:"उतारना", ro:"utaarna", en:"To take off", ic:"🧦"},
    {hi:"प्रेस करना", ro:"press karna", en:"To iron", ic:"👔"},
  ]},
  { id:"nature", name:"Nature & Weather", emoji:"🌳", words:[
    {hi:"मौसम", ro:"mausam", en:"Weather", ic:"🌤️"},
    {hi:"बारिश", ro:"baarish", en:"Rain", ic:"🌧️"},
    {hi:"धूप", ro:"dhoop", en:"Sunshine", ic:"🌞"},
    {hi:"बर्फ़", ro:"barf", en:"Snow / Ice", ic:"❄️"},
    {hi:"ठंड", ro:"thand", en:"Cold weather", ic:"🥶"},
    {hi:"गर्मी", ro:"garmi", en:"Hot weather / Summer", ic:"☀️"},
    {hi:"हवा", ro:"hawa", en:"Wind / Air", ic:"💨"},
    {hi:"बादल", ro:"baadal", en:"Clouds", ic:"☁️"},
    {hi:"आसमान", ro:"aasman", en:"Sky", ic:"🌌"},
    {hi:"चाँद", ro:"chaand", en:"Moon", ic:"🌙"},
    {hi:"सूरज", ro:"sooraj", en:"Sun", ic:"☀️"},
    {hi:"तारे", ro:"taare", en:"Stars", ic:"⭐"},
    {hi:"पेड़", ro:"ped", en:"Tree", ic:"🌳"},
    {hi:"पौधा", ro:"paudha", en:"Plant", ic:"🌱"},
    {hi:"फूल", ro:"phool", en:"Flower", ic:"🌸"},
    {hi:"पत्ता", ro:"patta", en:"Leaf", ic:"🍃"},
    {hi:"मिट्टी", ro:"mitti", en:"Soil / Mud", ic:"🟫"},
    {hi:"घास", ro:"ghaas", en:"Grass", ic:"🌿"},
    {hi:"बाग़", ro:"baagh", en:"Garden", ic:"🏡"},
    {hi:"नदी", ro:"nadi", en:"River", ic:"🏞️"},
    {hi:"पहाड़", ro:"pahaad", en:"Mountain", ic:"⛰️"},
    {hi:"समुंदर", ro:"samundar", en:"Ocean / Sea", ic:"🌊"},
    {hi:"झरना", ro:"jharna", en:"Waterfall", ic:"💦"},
    {hi:"जंगल", ro:"jungle", en:"Forest", ic:"🌲"},
    {hi:"खेत", ro:"khet", en:"Farm / Field", ic:"🌾"},
    {hi:"झील", ro:"jheel", en:"Lake", ic:"🛶"},
    {hi:"कीचड़", ro:"kichad", en:"Mud / Puddle", ic:"💧"},
    {hi:"तूफ़ान", ro:"toofan", en:"Storm", ic:"⛈️"},
    {hi:"बिजली", ro:"bijli", en:"Lightning / Electricity", ic:"⚡"},
    {hi:"इंद्रधनुष", ro:"indradhanush", en:"Rainbow", ic:"🌈"},
    {hi:"सूखा", ro:"sookha", en:"Dry", ic:"🏜️"},
    {hi:"गीला", ro:"geela", en:"Wet", ic:"💧"},
  ]},
  { id:"school", name:"School & Learning", emoji:"🏫", words:[
    {hi:"स्कूल", ro:"school", en:"School", ic:"🏫"},
    {hi:"टीचर", ro:"teacher", en:"Teacher", ic:"🧑‍🏫"},
    {hi:"क्लास", ro:"class", en:"Class", ic:"🧑‍🎓"},
    {hi:"दोस्त", ro:"dost", en:"Friend", ic:"🧑‍🤝‍🧑"},
    {hi:"पढ़ना", ro:"padhna", en:"To read / study", ic:"📖"},
    {hi:"लिखना", ro:"likhna", en:"To write", ic:"✍️"},
    {hi:"किताब", ro:"kitaab", en:"Book", ic:"📕"},
    {hi:"कॉपी", ro:"copy", en:"Notebook", ic:"📓"},
    {hi:"पेन", ro:"pen", en:"Pen", ic:"🖊️"},
    {hi:"पेंसिल", ro:"pencil", en:"Pencil", ic:"✏️"},
    {hi:"रबर", ro:"rubber", en:"Eraser", ic:"🧽"},
    {hi:"शार्पनर", ro:"sharpener", en:"Sharpener", ic:"📐"},
    {hi:"बैग / बस्ता", ro:"bag / Basta", en:"Backpack", ic:"🎒"},
    {hi:"होमवर्क", ro:"homework", en:"Homework", ic:"📝"},
    {hi:"टेस्ट / परीक्षा", ro:"test / Pariksha", en:"Test / Exam", ic:"📝"},
    {hi:"पास", ro:"pass", en:"Pass", ic:"✅"},
    {hi:"फ़ेल", ro:"fail", en:"Fail", ic:"❌"},
    {hi:"छुट्टी", ro:"chhutti", en:"Holiday / Break", ic:"🏖️"},
    {hi:"टिफिन", ro:"tiffin", en:"Lunchbox", ic:"🍱"},
    {hi:"बोर्ड", ro:"board", en:"Blackboard/Whiteboard", ic:"⬛"},
    {hi:"चाक", ro:"chalk", en:"Chalk", ic:"🖍️"},
    {hi:"डेस्क", ro:"desk", en:"Desk", ic:"🪑"},
    {hi:"कुर्सी", ro:"kursi", en:"Chair", ic:"🪑"},
    {hi:"सवाल", ro:"sawaal", en:"Question", ic:"❓"},
    {hi:"जवाब", ro:"jawaab", en:"Answer", ic:"💬"},
    {hi:"गलती", ro:"galti", en:"Mistake", ic:"❌"},
    {hi:"सही", ro:"sahi", en:"Right / Correct", ic:"✅"},
    {hi:"गलत", ro:"galat", en:"Wrong", ic:"❌"},
    {hi:"याद करना", ro:"yaad karna", en:"To memorize / remember", ic:"🧠"},
    {hi:"समझना", ro:"samajhna", en:"To understand", ic:"💡"},
    {hi:"कलर करना", ro:"color karna", en:"To color", ic:"🖍️"},
    {hi:"ड्राइंग", ro:"drawing", en:"Drawing", ic:"🎨"},
  ]},
  { id:"actions", name:"Action Words", emoji:"🏃", words:[
    {hi:"करना", ro:"karna", en:"To do", ic:"🤲"},
    {hi:"होना", ro:"hona", en:"To be / happen", ic:"✨"},
    {hi:"जाना", ro:"jaana", en:"To go", ic:"🚶"},
    {hi:"आना", ro:"aana", en:"To come", ic:"🏃"},
    {hi:"देखना", ro:"dekhna", en:"To watch / look", ic:"👀"},
    {hi:"सुनना", ro:"sunna", en:"To listen", ic:"👂"},
    {hi:"बोलना", ro:"bolna", en:"To speak", ic:"🗣️"},
    {hi:"बताना", ro:"batana", en:"To tell", ic:"💬"},
    {hi:"पूछना", ro:"poochhna", en:"To ask", ic:"🙋"},
    {hi:"बैठना", ro:"baithna", en:"To sit", ic:"🪑"},
    {hi:"खड़ा होना", ro:"khada hona", en:"To stand up", ic:"🧍"},
    {hi:"लाना", ro:"laana", en:"To bring", ic:"📥"},
    {hi:"रखना", ro:"rakhna", en:"To keep / put", ic:"📦"},
    {hi:"धोना", ro:"dhona", en:"To wash", ic:"🧼"},
    {hi:"साफ़ करना", ro:"saaf karna", en:"To clean", ic:"🧹"},
    {hi:"बंद करना", ro:"band karna", en:"To close", ic:"🔒"},
    {hi:"खोलना", ro:"kholna", en:"To open", ic:"🔓"},
    {hi:"सोचना", ro:"sochna", en:"To think", ic:"🤔"},
    {hi:"दौड़ना", ro:"daudna", en:"To run", ic:"🏃"},
    {hi:"चलना", ro:"chalna", en:"To walk", ic:"🚶"},
    {hi:"रुकना", ro:"rukna", en:"To stop", ic:"✋"},
    {hi:"ढूंढना", ro:"dhoondhna", en:"To look for / find", ic:"🔍"},
    {hi:"मिलना", ro:"milna", en:"To meet / find", ic:"🤝"},
    {hi:"बनाना", ro:"banaana", en:"To make / build", ic:"🔨"},
    {hi:"बुलाना", ro:"bulaana", en:"To call (someone)", ic:"📞"},
    {hi:"ख़रीदना", ro:"khareedna", en:"To buy", ic:"🛒"},
    {hi:"तैरना", ro:"tairna", en:"To swim", ic:"🏊"},
    {hi:"कूदना", ro:"koodna", en:"To jump", ic:"🤸"},
    {hi:"नाचना", ro:"naachna", en:"To dance", ic:"💃"},
    {hi:"गाना", ro:"gaana", en:"To sing", ic:"🎤"},
    {hi:"गिरना", ro:"girna", en:"To fall", ic:"⬇️"},
    {hi:"फेंकना", ro:"phekna", en:"To throw", ic:"🤾"},
    {hi:"पकड़ना", ro:"pakadna", en:"To catch", ic:"🧤"},
    {hi:"छुपना", ro:"chhupna", en:"To hide", ic:"🙈"},
    {hi:"चढ़ना", ro:"chadhna", en:"To climb", ic:"🧗"},
  ]},
  { id:"describe", name:"Describing & Opposites", emoji:"↔️", words:[
    {hi:"बड़ा", ro:"bada", en:"Big", ic:"🐘"},
    {hi:"छोटा", ro:"chhota", en:"Small", ic:"🐜"},
    {hi:"लम्बा", ro:"lamba", en:"Tall / Long", ic:"📏"},
    {hi:"नाटा", ro:"naata", en:"Short (Height)", ic:"📐"},
    {hi:"मोटा", ro:"mota", en:"Fat / Thick", ic:"🐷"},
    {hi:"पतला", ro:"patla", en:"Thin", ic:"🥢"},
    {hi:"नया", ro:"naya", en:"New", ic:"🆕"},
    {hi:"पुराना", ro:"purana", en:"Old (Things)", ic:"📜"},
    {hi:"अच्छा", ro:"achha", en:"Good", ic:"👍"},
    {hi:"बुरा", ro:"bura", en:"Bad", ic:"👎"},
    {hi:"साफ़", ro:"saaf", en:"Clean", ic:"✨"},
    {hi:"गंदा", ro:"ganda", en:"Dirty", ic:"🟤"},
    {hi:"गरम", ro:"garam", en:"Hot", ic:"🔥"},
    {hi:"ठंडा", ro:"thanda", en:"Cold", ic:"❄️"},
    {hi:"महँगा", ro:"mehanga", en:"Expensive", ic:"💰"},
    {hi:"सस्ता", ro:"sasta", en:"Cheap", ic:"🪙"},
    {hi:"आसान", ro:"aasaan", en:"Easy", ic:"😌"},
    {hi:"मुश्किल", ro:"mushkil", en:"Difficult", ic:"😣"},
    {hi:"सच", ro:"sach", en:"True / Truth", ic:"✅"},
    {hi:"झूठ", ro:"jhooth", en:"False / Lie", ic:"❌"},
    {hi:"तेज़", ro:"tez", en:"Fast / Sharp", ic:"⚡"},
    {hi:"धीरे", ro:"dheere", en:"Slow", ic:"🐢"},
    {hi:"भारी", ro:"bhaari", en:"Heavy", ic:"🏋️"},
    {hi:"हल्का", ro:"halka", en:"Light (Weight)", ic:"🪶"},
    {hi:"सही", ro:"sahi", en:"Right / Correct", ic:"✅"},
    {hi:"गलत", ro:"galat", en:"Wrong", ic:"❌"},
    {hi:"अंदर", ro:"andar", en:"Inside", ic:"📥"},
    {hi:"बाहर", ro:"baahar", en:"Outside", ic:"📤"},
    {hi:"ऊपर", ro:"oopar", en:"Up / Above", ic:"⬆️"},
    {hi:"नीचे", ro:"neeche", en:"Down / Below", ic:"⬇️"},
    {hi:"पास", ro:"paas", en:"Near", ic:"📍"},
    {hi:"दूर", ro:"door", en:"Far", ic:"🛣️"},
    {hi:"आगे", ro:"aage", en:"Front / Ahead", ic:"⏩"},
    {hi:"पीछे", ro:"peeche", en:"Back / Behind", ic:"⏪"},
    {hi:"खुला", ro:"khula", en:"Open", ic:"🔓"},
    {hi:"बंद", ro:"band", en:"Closed", ic:"🔒"},
  ]},
  { id:"time", name:"Time, Days & Months", emoji:"📅", words:[
    {hi:"टाइम / समय", ro:"time / Samay", en:"Time", ic:"⏰"},
    {hi:"बजे", ro:"baje", en:"O'clock", ic:"🕐"},
    {hi:"घंटा", ro:"ghanta", en:"Hour", ic:"⏳"},
    {hi:"मिनट", ro:"minute", en:"Minute", ic:"⏱️"},
    {hi:"सेकंड", ro:"second", en:"Second", ic:"⏲️"},
    {hi:"सुबह", ro:"subah", en:"Morning", ic:"🌅"},
    {hi:"दोपहर", ro:"dopahar", en:"Afternoon", ic:"☀️"},
    {hi:"शाम", ro:"shaam", en:"Evening", ic:"🌇"},
    {hi:"रात", ro:"raat", en:"Night", ic:"🌙"},
    {hi:"आज", ro:"aaj", en:"Today", ic:"📆"},
    {hi:"कल", ro:"kal", en:"Tomorrow / Yesterday", ic:"🗓️"},
    {hi:"परसों", ro:"parson", en:"Day after/before", ic:"📅"},
    {hi:"सोमवार", ro:"somvaar", en:"Monday", ic:"🌙"},
    {hi:"मंगलवार", ro:"mangalvaar", en:"Tuesday", ic:"🔥"},
    {hi:"बुधवार", ro:"budhvaar", en:"Wednesday", ic:"🌿"},
    {hi:"गुरुवार", ro:"guruvaar", en:"Thursday", ic:"⚡"},
    {hi:"शुक्रवार", ro:"shukravaar", en:"Friday", ic:"💛"},
    {hi:"शनिवार", ro:"shanivaar", en:"Saturday", ic:"🪐"},
    {hi:"रविवार", ro:"ravivaar", en:"Sunday", ic:"☀️"},
    {hi:"महीना", ro:"mahina", en:"Month", ic:"📆"},
    {hi:"साल", ro:"saal", en:"Year", ic:"🗓️"},
    {hi:"हफ़्ता", ro:"hafta", en:"Week", ic:"📅"},
    {hi:"जनवरी", ro:"january", en:"January", ic:"❄️"},
    {hi:"फरवरी", ro:"february", en:"February", ic:"💝"},
    {hi:"मार्च", ro:"march", en:"March", ic:"🌷"},
    {hi:"छुट्टी", ro:"chhutti", en:"Holiday", ic:"🏖️"},
    {hi:"जन्मदिन", ro:"janamdin", en:"Birthday", ic:"🎂"},
    {hi:"त्यौहार", ro:"tyohaar", en:"Festival", ic:"🎉"},
    {hi:"जल्दी", ro:"jaldi", en:"Early", ic:"⏰"},
    {hi:"देर", ro:"der", en:"Late", ic:"🐢"},
    {hi:"अभी", ro:"abhi", en:"Right now", ic:"⏱️"},
    {hi:"बाद में", ro:"baad mein", en:"Later", ic:"⏳"},
    {hi:"पहले", ro:"pehle", en:"Before / Earlier", ic:"⏪"},
  ]},
  { id:"places", name:"Places Around Town", emoji:"🏙️", words:[
    {hi:"दुकान", ro:"dukaan", en:"Shop / Store", ic:"🏪"},
    {hi:"मॉल", ro:"mall", en:"Mall", ic:"🏬"},
    {hi:"पार्क", ro:"park", en:"Park", ic:"🏞️"},
    {hi:"झूला", ro:"jhoola", en:"Swing / Theme Park Ride", ic:"🎡"},
    {hi:"होटल", ro:"hotel", en:"Hotel", ic:"🏨"},
    {hi:"ट्रेन", ro:"train", en:"Train", ic:"🚂"},
    {hi:"प्लेन", ro:"plane", en:"Airplane", ic:"✈️"},
    {hi:"घर", ro:"ghar", en:"Home", ic:"🏠"},
    {hi:"स्कूल", ro:"school", en:"School", ic:"🏫"},
    {hi:"अस्पताल", ro:"aspataal", en:"Hospital", ic:"🏥"},
    {hi:"क्लिनिक", ro:"clinic", en:"Clinic", ic:"🩺"},
    {hi:"बैंक", ro:"bank", en:"Bank", ic:"🏦"},
    {hi:"सिनेमा", ro:"cinema", en:"Movie Theater", ic:"🎬"},
    {hi:"रेस्टोरेंट", ro:"restaurant", en:"Restaurant", ic:"🍽️"},
    {hi:"मंदिर", ro:"mandir", en:"Temple", ic:"🛕"},
    {hi:"सुपरमार्केट", ro:"supermarket", en:"Supermarket", ic:"🛒"},
    {hi:"स्टेशन", ro:"station", en:"Station", ic:"🚉"},
    {hi:"एयरपोर्ट", ro:"airport", en:"Airport", ic:"🛫"},
    {hi:"बस स्टैंड", ro:"bus stand", en:"Bus stop", ic:"🚏"},
    {hi:"रास्ता", ro:"raasta", en:"Path / Way", ic:"🛤️"},
    {hi:"सड़क", ro:"sadak", en:"Road", ic:"🛣️"},
    {hi:"गली", ro:"gali", en:"Street / Lane", ic:"🏘️"},
    {hi:"चौराहा", ro:"chauraha", en:"Intersection", ic:"🚦"},
    {hi:"पड़ोस", ro:"pados", en:"Neighborhood", ic:"🏘️"},
    {hi:"शहर", ro:"sheher", en:"City", ic:"🏙️"},
    {hi:"गाँव", ro:"gaon", en:"Village / Town", ic:"🏡"},
    {hi:"पूल", ro:"pool", en:"Swimming Pool", ic:"🏊"},
    {hi:"तम्बू", ro:"tambu", en:"Tent / Camp", ic:"⛺"},
    {hi:"मेला", ro:"mela", en:"Fair / Carnival", ic:"🎪"},
    {hi:"बाज़ार", ro:"baazaar", en:"Market / Bazaar", ic:"🛍️"},
    {hi:"खेल का मैदान", ro:"khel ka maidan", en:"Playground", ic:"🛝"},
  ]},
];

const CONVOS = [
  { id:"c1", name:"Saying Hello", emoji:"👋", lines:[
    {sp:"A", hi:"नमस्ते!", ro:"namaste!", en:"Hello!"},
    {sp:"B", hi:"नमस्ते! तुम कैसी हो?", ro:"namaste! tum kaisi ho?", en:"Hello! How are you?"},
    {sp:"A", hi:"मैं ठीक हूँ, शुक्रिया। और तुम?", ro:"main theek hoon, shukriya. aur tum?", en:"I'm fine, thank you. And you?"},
    {sp:"B", hi:"मैं भी ठीक हूँ।", ro:"main bhi theek hoon.", en:"I'm fine too."},
    {sp:"A", hi:"फिर मिलेंगे!", ro:"phir milenge!", en:"See you again!"},
  ]},
  { id:"c2", name:"At Snack Time", emoji:"🍎", lines:[
    {sp:"A", hi:"मुझे भूख लगी है।", ro:"mujhe bhookh lagi hai.", en:"I am hungry."},
    {sp:"B", hi:"क्या तुम्हें सेब चाहिए?", ro:"kya tumhein seb chahiye?", en:"Do you want an apple?"},
    {sp:"A", hi:"हाँ, कृपया!", ro:"haan, kripya!", en:"Yes, please!"},
    {sp:"B", hi:"यह लो।", ro:"yeh lo.", en:"Here you go."},
    {sp:"A", hi:"बहुत स्वादिष्ट है। शुक्रिया!", ro:"bahut swaadisht hai. shukriya!", en:"It's very tasty. Thank you!"},
  ]},
  { id:"c3", name:"Meeting a Friend", emoji:"🧒", lines:[
    {sp:"A", hi:"तुम्हारा नाम क्या है?", ro:"tumhara naam kya hai?", en:"What's your name?"},
    {sp:"B", hi:"मेरा नाम आरिया है। और तुम्हारा?", ro:"mera naam Aria hai. aur tumhara?", en:"My name is Aria. And yours?"},
    {sp:"A", hi:"मेरा नाम रवि है।", ro:"mera naam Ravi hai.", en:"My name is Ravi."},
    {sp:"B", hi:"आपसे मिलकर खुशी हुई!", ro:"aapse milkar khushi hui!", en:"Nice to meet you!"},
    {sp:"A", hi:"चलो खेलते हैं!", ro:"chalo khelte hain!", en:"Let's play!"},
  ]},
  { id:"c4", name:"Good Morning", emoji:"🌅", lines:[
    {sp:"A", hi:"शुभ प्रभात!", ro:"shubh prabhaat!", en:"Good morning!"},
    {sp:"B", hi:"शुभ प्रभात! क्या तुम उठ गई?", ro:"shubh prabhaat! kya tum uth gayi?", en:"Good morning! Did you wake up?"},
    {sp:"A", hi:"हाँ, मैं तैयार हूँ।", ro:"haan, main taiyaar hoon.", en:"Yes, I am ready."},
    {sp:"B", hi:"चलो नाश्ता करते हैं।", ro:"chalo naashta karte hain.", en:"Let's eat breakfast."},
    {sp:"A", hi:"मुझे दूध चाहिए।", ro:"mujhe doodh chahiye.", en:"I want milk."},
  ]},
  { id:"c5", name:"At the Park", emoji:"🏞️", lines:[
    {sp:"A", hi:"चलो पार्क चलते हैं।", ro:"chalo park chalte hain.", en:"Let's go to the park."},
    {sp:"B", hi:"मैं झूला झूलना चाहती हूँ।", ro:"main jhoola jhoolna chahti hoon.", en:"I want to swing."},
    {sp:"A", hi:"मैं फिसलपट्टी पर खेलूँगी।", ro:"main phisalpatti par kheloongi.", en:"I will play on the slide."},
    {sp:"B", hi:"देखो, कितनी सुंदर तितली!", ro:"dekho, kitni sundar titli!", en:"Look, what a beautiful butterfly!"},
    {sp:"A", hi:"बहुत मज़ा आ रहा है!", ro:"bahut mazaa aa raha hai!", en:"This is so much fun!"},
  ]},
  { id:"c6", name:"Bedtime", emoji:"🌙", lines:[
    {sp:"A", hi:"मुझे नींद आ रही है।", ro:"mujhe neend aa rahi hai.", en:"I am feeling sleepy."},
    {sp:"B", hi:"चलो सोने का समय हो गया।", ro:"chalo sone ka samay ho gaya.", en:"Come, it's time to sleep."},
    {sp:"A", hi:"क्या तुम मुझे कहानी सुनाओगी?", ro:"kya tum mujhe kahaani sunaaogi?", en:"Will you tell me a story?"},
    {sp:"B", hi:"हाँ, ज़रूर।", ro:"haan, zaroor.", en:"Yes, of course."},
    {sp:"A", hi:"शुभ रात्रि!", ro:"shubh raatri!", en:"Good night!"},
  ]},
  { id:"c7", name:"Helping Mom", emoji:"🤝", lines:[
    {sp:"A", hi:"माँ, क्या मैं मदद करूँ?", ro:"maa, kya main madad karoon?", en:"Mom, shall I help?"},
    {sp:"B", hi:"हाँ, कृपया मेज़ साफ़ करो।", ro:"haan, kripya mez saaf karo.", en:"Yes, please clean the table."},
    {sp:"A", hi:"ठीक है, हो गया।", ro:"theek hai, ho gaya.", en:"Okay, it's done."},
    {sp:"B", hi:"शाबाश! तुम बहुत अच्छी हो।", ro:"shaabaash! tum bahut achhi ho.", en:"Well done! You are very good."},
    {sp:"A", hi:"धन्यवाद, माँ!", ro:"dhanyavaad, maa!", en:"Thank you, Mom!"},
  ]},
  { id:"c8", name:"What's Your Favorite?", emoji:"❤️", lines:[
    {sp:"A", hi:"तुम्हारा पसंदीदा रंग कौन सा है?", ro:"tumhara pasandeeda rang kaun sa hai?", en:"What is your favorite color?"},
    {sp:"B", hi:"मुझे गुलाबी रंग पसंद है।", ro:"mujhe gulaabi rang pasand hai.", en:"I like the color pink."},
    {sp:"A", hi:"तुम्हारा पसंदीदा फल क्या है?", ro:"tumhara pasandeeda phal kya hai?", en:"What is your favorite fruit?"},
    {sp:"B", hi:"मुझे आम बहुत पसंद हैं।", ro:"mujhe aam bahut pasand hain.", en:"I really like mangoes."},
    {sp:"A", hi:"मुझे भी!", ro:"mujhe bhi!", en:"Me too!"},
  ]},
  { id:"c9", name:"Feeling Sick", emoji:"🤒", lines:[
    {sp:"A", hi:"मेरी तबीयत ठीक नहीं है।", ro:"meri tabiyat theek nahin hai.", en:"I am not feeling well."},
    {sp:"B", hi:"क्या हुआ? कहाँ दर्द है?", ro:"kya hua? kahaan dard hai?", en:"What happened? Where does it hurt?"},
    {sp:"A", hi:"मेरे सिर में दर्द है।", ro:"mere sir mein dard hai.", en:"My head hurts."},
    {sp:"B", hi:"आराम करो, सब ठीक हो जाएगा।", ro:"aaraam karo, sab theek ho jaayega.", en:"Rest, everything will be fine."},
    {sp:"A", hi:"शुक्रिया।", ro:"shukriya.", en:"Thank you."},
  ]},
  { id:"c10", name:"At the Market", emoji:"🛒", lines:[
    {sp:"A", hi:"हमें क्या खरीदना है?", ro:"hamein kya khareedna hai?", en:"What do we need to buy?"},
    {sp:"B", hi:"हमें सेब और दूध चाहिए।", ro:"hamein seb aur doodh chahiye.", en:"We need apples and milk."},
    {sp:"A", hi:"यह कितने का है?", ro:"yeh kitne ka hai?", en:"How much is this?"},
    {sp:"B", hi:"यह बीस रुपये का है।", ro:"yeh bees rupaye ka hai.", en:"This is twenty rupees."},
    {sp:"A", hi:"ठीक है, हम इसे लेंगे।", ro:"theek hai, hum ise lenge.", en:"Okay, we'll take it."},
  ]},
];

/* ===== GRAMMAR: build-the-sentence lessons ===== */
const GRAMMAR = [
  { id:"order", name:"Verb Goes Last", emoji:"🔤",
    tip:"In Hindi the verb comes LAST. English: I eat an apple. Hindi: I — apple — eat (मैं सेब खाती हूँ).",
    examples:[
      {hi:"मैं सेब खाती हूँ", ro:"main seb khaati hoon", en:"I eat an apple"},
      {hi:"वह पानी पीता है", ro:"vah paani peeta hai", en:"He drinks water"},
      {hi:"हम खेल खेलते हैं", ro:"hum khel khelte hain", en:"We play a game"},
    ],
    builds:[
      {en:"I eat an apple", words:["मैं","सेब","खाती","हूँ"], ro:"main seb khaati hoon"},
      {en:"He drinks water", words:["वह","पानी","पीता","है"], ro:"vah paani peeta hai"},
      {en:"I read a book", words:["मैं","किताब","पढ़ती","हूँ"], ro:"main kitaab padhti hoon"},
    ]},
  { id:"tobe", name:"I am / You are", emoji:"🙋",
    tip:"To say 'am/is/are' use होना: मैं हूँ (I am), तुम हो (you are), वह है (he/she is), हम हैं (we are).",
    examples:[
      {hi:"मैं खुश हूँ", ro:"main khush hoon", en:"I am happy"},
      {hi:"तुम अच्छे हो", ro:"tum achhe ho", en:"You are good"},
      {hi:"हम तैयार हैं", ro:"hum taiyaar hain", en:"We are ready"},
    ],
    builds:[
      {en:"I am happy", words:["मैं","खुश","हूँ"], ro:"main khush hoon"},
      {en:"You are my friend", words:["तुम","मेरे","दोस्त","हो"], ro:"tum mere dost ho"},
      {en:"We are ready", words:["हम","तैयार","हैं"], ro:"hum taiyaar hain"},
    ]},
  { id:"thisthat", name:"This is / That is", emoji:"👉",
    tip:"यह = this, वह = that. Add है at the end: यह सेब है (This is an apple).",
    examples:[
      {hi:"यह सेब है", ro:"yeh seb hai", en:"This is an apple"},
      {hi:"वह बिल्ली है", ro:"vah billi hai", en:"That is a cat"},
      {hi:"यह मेरी किताब है", ro:"yeh meri kitaab hai", en:"This is my book"},
    ],
    builds:[
      {en:"This is a dog", words:["यह","कुत्ता","है"], ro:"yeh kutta hai"},
      {en:"That is my house", words:["वह","मेरा","घर","है"], ro:"vah mera ghar hai"},
    ]},
  { id:"present", name:"Doing It Now", emoji:"🏃",
    tip:"For things you do, add ती (girl) or ता (boy) to the verb, then हूँ/है. Aria is a girl, so she uses ती: मैं खाती हूँ (I eat).",
    examples:[
      {hi:"मैं पढ़ती हूँ", ro:"main padhti hoon", en:"I study"},
      {hi:"मैं गाती हूँ", ro:"main gaati hoon", en:"I sing"},
      {hi:"तुम खेलते हो", ro:"tum khelte ho", en:"You play"},
    ],
    builds:[
      {en:"I study", words:["मैं","पढ़ती","हूँ"], ro:"main padhti hoon"},
      {en:"I drink milk", words:["मैं","दूध","पीती","हूँ"], ro:"main doodh peeti hoon"},
      {en:"I go to school", words:["मैं","स्कूल","जाती","हूँ"], ro:"main school jaati hoon"},
    ]},
  { id:"poss", name:"My / Your", emoji:"🫳",
    tip:"मेरा/मेरी = my, तुम्हारा/तुम्हारी = your. Match girl-words with मेरी: मेरी माँ (my mom), मेरा भाई (my brother).",
    examples:[
      {hi:"मेरी माँ", ro:"meri maa", en:"my mom"},
      {hi:"मेरा दोस्त", ro:"mera dost", en:"my friend"},
      {hi:"तुम्हारा नाम", ro:"tumhara naam", en:"your name"},
    ],
    builds:[
      {en:"This is my mom", words:["यह","मेरी","माँ","है"], ro:"yeh meri maa hai"},
      {en:"What is your name?", words:["तुम्हारा","नाम","क्या","है"], ro:"tumhara naam kya hai"},
    ]},
  { id:"post", name:"In / On / To", emoji:"📍",
    tip:"Hindi puts these AFTER the word: में = in, पर = on, को = to. घर में (in the house), मेज़ पर (on the table).",
    examples:[
      {hi:"घर में", ro:"ghar mein", en:"in the house"},
      {hi:"मेज़ पर", ro:"mez par", en:"on the table"},
      {hi:"मैं स्कूल को जाती हूँ", ro:"main school ko jaati hoon", en:"I go to school"},
    ],
    builds:[
      {en:"The book is on the table", words:["किताब","मेज़","पर","है"], ro:"kitaab mez par hai"},
      {en:"Mom is in the house", words:["माँ","घर","में","है"], ro:"maa ghar mein hai"},
    ]},
  { id:"quest", name:"Asking Questions", emoji:"❓",
    tip:"Put क्या at the start for yes/no questions: क्या तुम खुश हो? Use कहाँ (where), क्या (what), कौन (who).",
    examples:[
      {hi:"क्या तुम खुश हो?", ro:"kya tum khush ho?", en:"Are you happy?"},
      {hi:"तुम कहाँ हो?", ro:"tum kahaan ho?", en:"Where are you?"},
      {hi:"यह क्या है?", ro:"yeh kya hai?", en:"What is this?"},
    ],
    builds:[
      {en:"Are you ready?", words:["क्या","तुम","तैयार","हो"], ro:"kya tum taiyaar ho"},
      {en:"Where is mom?", words:["माँ","कहाँ","है"], ro:"maa kahaan hai"},
    ]},
  { id:"neg", name:"Saying No", emoji:"🙅",
    tip:"Add नहीं before the verb to say 'not'. यह बिल्ली नहीं है (This is not a cat). मैं उदास नहीं हूँ (I am not sad).",
    examples:[
      {hi:"यह मेरा नहीं है", ro:"yeh mera nahin hai", en:"This is not mine"},
      {hi:"मुझे यह पसंद नहीं है", ro:"mujhe yeh pasand nahin hai", en:"I don't like this"},
      {hi:"मैं नहीं जाती", ro:"main nahin jaati", en:"I don't go"},
    ],
    builds:[
      {en:"This is not a cat", words:["यह","बिल्ली","नहीं","है"], ro:"yeh billi nahin hai"},
      {en:"I am not sad", words:["मैं","उदास","नहीं","हूँ"], ro:"main udaas nahin hoon"},
    ]},
  { id:"plural", name:"More Than One", emoji:"🔢",
    tip:"Many boy-words change ा→े: लड़का→लड़के (boys). Many girl-words add ें: किताब→किताबें (books).",
    examples:[
      {hi:"दो लड़के", ro:"do ladke", en:"two boys"},
      {hi:"तीन किताबें", ro:"teen kitaabein", en:"three books"},
      {hi:"बहुत फूल", ro:"bahut phool", en:"many flowers"},
    ],
    builds:[
      {en:"two boys", words:["दो","लड़के"], ro:"do ladke"},
      {en:"three books", words:["तीन","किताबें"], ro:"teen kitaabein"},
    ]},
  { id:"gender", name:"Boy & Girl Words", emoji:"⚖️",
    tip:"Words are 'boy' or 'girl', and the describing word matches: अच्छा लड़का (good boy), अच्छी लड़की (good girl).",
    examples:[
      {hi:"अच्छा लड़का", ro:"achha ladka", en:"good boy"},
      {hi:"अच्छी लड़की", ro:"achhi ladki", en:"good girl"},
      {hi:"बड़ा घर", ro:"bada ghar", en:"big house"},
    ],
    builds:[
      {en:"good girl", words:["अच्छी","लड़की"], ro:"achhi ladki"},
      {en:"big house", words:["बड़ा","घर"], ro:"bada ghar"},
    ]},
  { id:"past", name:"What Happened", emoji:"⏪",
    tip:"For the past, the verb changes: जाना→गई (a girl went). मैं स्कूल गई (I went to school).",
    examples:[
      {hi:"मैं स्कूल गई", ro:"main school gayi", en:"I went to school"},
      {hi:"हम पार्क गए", ro:"hum park gaye", en:"We went to the park"},
      {hi:"उसने खाना खाया", ro:"usne khaana khaaya", en:"He ate food"},
    ],
    builds:[
      {en:"I went to school", words:["मैं","स्कूल","गई"], ro:"main school gayi"},
      {en:"We went to the park", words:["हम","पार्क","गए"], ro:"hum park gaye"},
    ]},
  { id:"want", name:"I Want / I Need", emoji:"🙏",
    tip:"To say 'I want' use मुझे … चाहिए. मुझे पानी चाहिए (I want water). मुझे मदद चाहिए (I need help).",
    examples:[
      {hi:"मुझे पानी चाहिए", ro:"mujhe paani chahiye", en:"I want water"},
      {hi:"मुझे मदद चाहिए", ro:"mujhe madad chahiye", en:"I need help"},
      {hi:"मुझे यह चाहिए", ro:"mujhe yeh chahiye", en:"I want this"},
    ],
    builds:[
      {en:"I want milk", words:["मुझे","दूध","चाहिए"], ro:"mujhe doodh chahiye"},
      {en:"I need help", words:["मुझे","मदद","चाहिए"], ro:"mujhe madad chahiye"},
    ]},
];

/* ===== ARENA GAMES: neon grammar mini-games ===== */
const GAMES = [
  { id:"aura", name:"Aura Match", emoji:"🌈", type:"aura",
    intro:"Boy words & boy verb-endings glow CYAN 🩵. Girl ones glow MAGENTA 🩷. Aria is a girl, so for herself she taps the magenta ending! Match the aura to land the hit.",
    rounds:[
      {en:"I (a girl) am playing", prompt:"मैं खेल ___", optF:"रही हूँ", optM:"रहा हूँ", ans:"f"},
      {en:"I (a girl) eat food", prompt:"मैं खाना खा ___", optF:"ती हूँ", optM:"ता हूँ", ans:"f"},
      {en:"I (a girl) will go", prompt:"मैं ___", optF:"जाऊँगी", optM:"जाऊँगा", ans:"f"},
      {en:"That BOY is running", prompt:"वह लड़का दौड़ ___", optF:"रही है", optM:"रहा है", ans:"m"},
      {en:"That GIRL is reading", prompt:"वह लड़की पढ़ ___", optF:"रही है", optM:"रहा है", ans:"f"},
      {en:"I (a girl) am good", prompt:"मैं ___ हूँ", optF:"अच्छी", optM:"अच्छा", ans:"f"},
      {en:"That BOY is good", prompt:"वह लड़का ___ है", optF:"अच्छी", optM:"अच्छा", ans:"m"},
      {en:"I (a girl) sing", prompt:"मैं गा ___", optF:"ती हूँ", optM:"ता हूँ", ans:"f"},
    ]},
  { id:"combo", name:"Combo Chains", emoji:"🥷", type:"combo",
    intro:"Hindi attacks in order: Fighter (who) → Target (what) → Attack (verb). Put the VERB last to land a Critical Hit! 💥",
    rounds:[
      {en:"I eat an apple", s:"मैं", o:"सेब", v:"खाती हूँ"},
      {en:"I drink milk", s:"मैं", o:"दूध", v:"पीती हूँ"},
      {en:"She reads a book", s:"वह", o:"किताब", v:"पढ़ती है"},
      {en:"We play a game", s:"हम", o:"खेल", v:"खेलते हैं"},
      {en:"I see the moon", s:"मैं", o:"चाँद", v:"देखती हूँ"},
      {en:"I want water", s:"मुझे", o:"पानी", v:"चाहिए"},
    ]},
  { id:"respect", name:"Respect Shield", emoji:"🛡️", type:"respect",
    intro:"Elders, teachers & grandparents get the polite Aap 🛡️ shield to show respect. Friends & younger kids use the casual Tum ⚔️. Pick the right stance!",
    rounds:[
      {scenario:"Ask Nani (grandma) for water 👵", who:"elder", aap:"आप पानी दीजिए", tum:"तुम पानी दो"},
      {scenario:"Ask your friend to play 🧒", who:"friend", aap:"आप खेलिए", tum:"तुम खेलो"},
      {scenario:"Greet your teacher 🧑‍🏫", who:"elder", aap:"आप कैसे हैं?", tum:"तुम कैसे हो?"},
      {scenario:"Tell your little brother to come 👦", who:"friend", aap:"आप आइए", tum:"तुम आओ"},
      {scenario:"Tell Dadaji (grandpa) to sit 👴", who:"elder", aap:"आप बैठिए", tum:"तुम बैठो"},
      {scenario:"Call your best friend 🧒", who:"friend", aap:"आप सुनिए", tum:"तुम सुनो"},
    ]},
  { id:"runes", name:"Time Runes", emoji:"⏳", type:"runes",
    intro:"Verbs are your weapons. Snap on a time rune: ⚡ NOW (happening), 🌑 DONE (past), or ✨ LATER (future). Tap the verb form that matches!",
    rounds:[
      {verb:"play", ask:"future", present:"खेल रही हूँ", past:"खेली", future:"खेलूँगी"},
      {verb:"go", ask:"now", present:"जा रही हूँ", past:"गई", future:"जाऊँगी"},
      {verb:"sleep", ask:"past", present:"सो रही हूँ", past:"सोई", future:"सोऊँगी"},
      {verb:"come", ask:"future", present:"आ रही हूँ", past:"आई", future:"आऊँगी"},
      {verb:"dance", ask:"now", present:"नाच रही हूँ", past:"नाची", future:"नाचूँगी"},
      {verb:"sing", ask:"past", present:"गा रही हूँ", past:"गाई", future:"गाऊँगी"},
    ]},
  { id:"potion", name:"Potion Lab", emoji:"⚗️", type:"potion",
    intro:"Hindi puts in/on/to AFTER the word, like a catalyst dropped in last: घर में (in the house). Brew the potion — add the right catalyst after the noun!",
    rounds:[
      {en:"in the house", noun:"घर", post:"में", opts:["में","पर","को"]},
      {en:"on the table", noun:"मेज़", post:"पर", opts:["पर","में","से"]},
      {en:"in the closet", noun:"अलमारी", post:"में", opts:["में","पर","को"]},
      {en:"on the bed", noun:"बिस्तर", post:"पर", opts:["पर","में","को"]},
      {en:"to school", noun:"स्कूल", post:"को", opts:["को","में","पर"]},
      {en:"in the water", noun:"पानी", post:"में", opts:["में","पर","से"]},
    ]},
];

if (typeof window !== "undefined") { window.UNITS = UNITS; window.CONVOS = CONVOS; window.GRAMMAR = GRAMMAR; window.GAMES = GAMES; }
